export const sellerList: Seller[] = [
  {
    _id: 'fawdhjLKwdrwe1',
    marketName: '가게이름1',
    images: [
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
    ],
    lat: 37.439811,
    lng: 127.12798,
    location: '경기도 성남시 수정구 성남대로1237번길 8-21',
    sellerName: '셀러1',
    id: 'seller1',
    pw: 'password1',
    businessNumber: 12345678901,
    mutualName: '상호명1',
    startDay: 'mon',
    endDay: 'fri',
    startTime: '10:00',
    endTime: '20:00',
    originalInfo: '정보1',
    introduction: '소개글1',
    openedAt: new Date(),
    closedAt: new Date(),
    mininumReservationDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'fawdhjLKwdrwe2',
    marketName: '가게이름2',
    images: [
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
    ],
    lat: 37.540123,
    lng: 127.056321,
    location: '서울특별시 강남구 테헤란로 123',
    sellerName: '셀러2',
    id: 'seller2',
    pw: 'password2',
    businessNumber: 23456789012,
    mutualName: '상호명2',
    startDay: 'tue',
    endDay: 'sat',
    startTime: '09:00',
    endTime: '19:00',
    originalInfo: '정보2',
    introduction: '소개글2',
    openedAt: new Date(),
    closedAt: new Date(),
    mininumReservationDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'fawdhjLKwdrwe3',
    marketName: '가게이름3',
    images: [
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
    ],
    lat: 37.620456,
    lng: 127.099876,
    location: '서울특별시 서초구 서초대로 456',
    sellerName: '셀러3',
    id: 'seller3',
    pw: 'password3',
    businessNumber: 34567890123,
    mutualName: '상호명3',
    startDay: 'wed',
    endDay: 'sun',
    startTime: '08:30',
    endTime: '22:00',
    originalInfo: '정보3',
    introduction: '소개글3',
    openedAt: new Date(),
    closedAt: new Date(),
    mininumReservationDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'fawdhjLKwdrwe4',
    marketName: '가게이름4',
    images: [
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
    ],
    lat: 37.665789,
    lng: 127.145678,
    location: '경기도 수원시 영통구 영통로 789',
    sellerName: '셀러4',
    id: 'seller4',
    pw: 'password4',
    businessNumber: 45678901234,
    mutualName: '상호명4',
    startDay: 'thu',
    endDay: 'mon',
    startTime: '11:00',
    endTime: '21:30',
    originalInfo: '정보4',
    introduction: '소개글4',
    openedAt: new Date(),
    closedAt: new Date(),
    mininumReservationDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'fawdhjLKwdrwe5',
    marketName: '가게이름5',
    images: [
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
      'https://placehold.co/600x400',
    ],
    lat: 37.712345,
    lng: 127.189012,
    location: '경기도 부천시 부천로 111',
    sellerName: '셀러5',
    id: 'seller5',
    pw: 'password5',
    businessNumber: 56789012345,
    mutualName: '상호명5',
    startDay: 'fri',
    endDay: 'tue',
    startTime: '07:30',
    endTime: '18:30',
    originalInfo: '정보5',
    introduction: '소개글5',
    openedAt: new Date(),
    closedAt: new Date(),
    mininumReservationDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
