packages:
  - "packages/studio"
  - "packages/administration"
  - "packages/package"
  - "packages/blog"
  - "packages/voca"
  - "packages/mongo"
  - "packages/chamlangapi"
  - "packages/lettering"
  - "packages/pick-pic"
