export interface Verb {
  stemjp: string;
  stemro: string;
  endingjp: string;
  endingro: string;
  form?: number;
  exception: boolean;
}

export interface Noun {
  ko: string;
  jp: string;
}

export interface Example {
  jp: string;
  ko: string;
}

export interface Adverb {}

export interface Word<T> {
  id?: string;
  ko: string;
  jp: string;
  kana: string;
  ro: string;
  type: 'verb' | 'noun' | 'adv' | 'adj';
  language: string;
  etc?: T;
  example?: Example[];
}

export const typeGbn = {
  verb: '동사',
  noun: '명사',
  adv: '부사',
  adj: '형용사',
};

export const adv = [
  {
    language: 'japanese',
    ko: '곧',
    jp: 'すぐ',
    kana: 'すぐ',
    ro: 'sugu',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '항상',
    jp: 'いつも',
    kana: 'いつも',
    ro: 'itsumo',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '많이',
    jp: 'たくさん',
    kana: 'たくさん',
    ro: 'takusan',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '매우',
    jp: 'とても',
    kana: 'とても',
    ro: 'totemo',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '별로',
    jp: 'あまり',
    kana: 'あまり',
    ro: 'amari',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '전혀',
    jp: '全然',
    kana: 'ぜんぜん',
    ro: 'zenzen',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이미',
    jp: 'もう',
    kana: 'もう',
    ro: 'mou',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '아직',
    jp: 'まだ',
    kana: 'まだ',
    ro: 'mada',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자주',
    jp: 'よく',
    kana: 'よく',
    ro: 'yoku',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가끔',
    jp: 'たまに',
    kana: 'たまに',
    ro: 'tamani',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '때때로',
    jp: '時々',
    kana: 'ときどき',
    ro: 'tokidoki',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이미',
    jp: 'すでに',
    kana: 'すでに',
    ro: 'sudeni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '갑자기',
    jp: '急に',
    kana: 'きゅうに',
    ro: 'kyuu ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '천천히',
    jp: 'ゆっくり',
    kana: 'ゆっくり',
    ro: 'yukkuri',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조용히',
    jp: '静かに',
    kana: 'しずかに',
    ro: 'shizuka ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '분명히',
    jp: '明らかに',
    kana: 'あきらかに',
    ro: 'akiraka ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '확실히',
    jp: '確かに',
    kana: 'たしかに',
    ro: 'tashika ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '특히',
    jp: '特に',
    kana: 'とくに',
    ro: 'toku ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '전혀',
    jp: '全く',
    kana: 'まったく',
    ro: 'mattaku',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조금',
    jp: '少し',
    kana: 'すこし',
    ro: 'sukoshi',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '충분히',
    jp: 'たっぷり',
    kana: 'たっぷり',
    ro: 'tappuri',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '완전히',
    jp: 'すっかり',
    kana: 'すっかり',
    ro: 'sukkari',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '확실히',
    jp: 'しっかり',
    kana: 'しっかり',
    ro: 'shikkari',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '느리게',
    jp: 'ゆっくり',
    kana: 'ゆっくり',
    ro: 'yukkuri',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '즉시',
    jp: 'すぐに',
    kana: 'すぐに',
    ro: 'sugu ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '언젠가',
    jp: 'いつか',
    kana: 'いつか',
    ro: 'itsuka',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가끔',
    jp: 'たまに',
    kana: 'たまに',
    ro: 'tamani',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자주',
    jp: 'しばしば',
    kana: 'しばしば',
    ro: 'shibashiba',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '아마도',
    jp: 'おそらく',
    kana: 'おそらく',
    ro: 'osoraku',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '아마',
    jp: 'おそらく',
    kana: 'おそらく',
    ro: 'osoraku',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '확실히',
    jp: '確実に',
    kana: 'かくじつに',
    ro: 'kakujitsu ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '천천히',
    jp: 'ゆっくりと',
    kana: 'ゆっくりと',
    ro: 'yukkuri to',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '즉시',
    jp: 'すぐさま',
    kana: 'すぐさま',
    ro: 'sugu sama',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '함께',
    jp: '一緒に',
    kana: 'いっしょに',
    ro: 'issho ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '한 번',
    jp: '一度',
    kana: 'いちど',
    ro: 'ichido',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '두 번',
    jp: '二度',
    kana: 'にど',
    ro: 'nido',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '세 번',
    jp: '三度',
    kana: 'さんど',
    ro: 'sando',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '많은',
    jp: 'たくさんの',
    kana: 'たくさんの',
    ro: 'takusan no',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조금씩',
    jp: '少しずつ',
    kana: 'すこしずつ',
    ro: 'sukoshi zutsu',
    type: 'adv',
    example: [],
  },
];

export const adj = [
  {
    id: '',
    language: 'japanese',
    ko: '두껍다',
    jp: '厚い',
    kana: 'あつい',
    ro: 'atsui',
    type: 'adj',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '厚',
      stemro: 'atsu',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '수상하다',
    jp: '怪しい',
    kana: 'あやしい',
    ro: 'ayashii',
    type: 'adj',
    etc: {
      endingjp: 'しい',
      endingro: 'shii',
      exception: false,
      form: 'i',
      stemjp: '怪',
      stemro: 'aya',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '얇다, 엷다',
    jp: '薄い',
    kana: 'うすい',
    ro: 'usui',
    type: 'adj',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '薄',
      stemro: 'usu',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '훌륭하다, 위대하다',
    jp: '偉い',
    kana: 'えらい',
    ro: 'erai',
    type: 'adj',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '偉',
      stemro: 'era',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '아깝다, 애석하다',
    jp: '惜しい',
    kana: 'おしい',
    ro: 'oshii',
    type: 'adj',
    etc: {
      endingjp: 'しい',
      endingro: 'shii',
      exception: false,
      form: 'i',
      stemjp: '惜',
      stemro: 'o',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '힘들다',
    jp: '苦しい',
    kana: 'くるしい',
    ro: 'kurushii',
    type: 'adj',
    etc: {
      endingjp: 'しい',
      endingro: 'shii',
      exception: false,
      form: 'i',
      stemjp: '苦',
      stemro: 'kuru',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '자세하다, 상세하다, 잘 알고 있다',
    jp: '詳しい',
    kana: 'くわしい',
    ro: 'kuwashii',
    type: 'adj',
    etc: {
      endingjp: 'しい',
      endingro: 'shii',
      exception: false,
      form: 'i',
      stemjp: '詳',
      stemro: 'kuwa',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '그립다',
    jp: '恋しい',
    kana: 'こいしい',
    ro: 'koishii',
    type: 'adj',
    etc: {
      endingjp: 'しい',
      endingro: 'shii',
      exception: false,
      form: 'i',
      stemjp: '恋',
      stemro: 'koi',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '잘다, 작다, 세세하다',
    jp: '細かい',
    kana: 'こまかい',
    ro: 'komakai',
    type: 'adj',
    etc: {
      endingjp: 'かい',
      endingro: 'kai',
      exception: false,
      form: 'i',
      stemjp: '細ま',
      stemro: 'koma',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '친하다',
    jp: '親しい',
    kana: 'したしい',
    ro: 'shitashii',
    type: 'adj',
    etc: {
      endingjp: 'しい',
      endingro: 'shii',
      exception: false,
      form: 'i',
      stemjp: '親',
      stemro: 'shita',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '가늘다',
    jp: '細い',
    kana: 'ほそい',
    ro: 'hosoi',
    type: 'adj',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '細',
      stemro: 'hoso',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '둥글다',
    jp: '丸い',
    kana: 'まるい',
    ro: 'marui',
    type: 'adj',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '丸',
      stemro: 'maru',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '짧다',
    jp: '短い',
    kana: 'みじかい',
    ro: 'mijikai',
    type: 'adj',
    etc: {
      endingjp: 'かい',
      endingro: 'kai',
      exception: false,
      form: 'i',
      stemjp: '短じ',
      stemro: 'miji',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '쉽다',
    jp: '易しい',
    kana: 'やさしい',
    ro: 'yasashii',
    type: 'adj',
    etc: {
      endingjp: 'しい',
      endingro: 'shii',
      exception: false,
      form: 'i',
      stemjp: '易',
      stemro: 'yasa',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '느슨하다, 엄하지 않다',
    jp: '緩い',
    kana: 'ゆるい',
    ro: 'yurui',
    type: 'adj',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '緩',
      stemro: 'yuru',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '젊다',
    jp: '若い',
    kana: 'わかい',
    ro: 'wakai',
    type: 'adj',
    etc: {
      endingjp: 'かい',
      endingro: 'kai',
      exception: false,
      form: 'i',
      stemjp: '若',
      stemro: 'wa',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '일반적이다',
    jp: '一般的だ',
    kana: 'いっぱんてきだ',
    ro: 'ippantekida',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '一般的',
      stemro: 'ippanteki',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '주되다',
    jp: '主だ',
    kana: 'おもだ',
    ro: 'omoda',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '主',
      stemro: 'omo',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '확실하다',
    jp: '確実だ',
    kana: 'かくじつだ',
    ro: 'kakujitsuda',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '確実',
      stemro: 'kakujitsu',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '감정적이다',
    jp: '感情的だ',
    kana: 'かんじょうてきだ',
    ro: 'kanjoutekida',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '感情的',
      stemro: 'kanjouteki',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '간단하다',
    jp: '簡単だ',
    kana: 'かんたんだ',
    ro: 'kantanda',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '簡単',
      stemro: 'kantan',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '구체적이다',
    jp: '具体的だ',
    kana: 'ぐたいてきだ',
    ro: 'gutaitekida',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '具体的',
      stemro: 'gutaiteki',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '활발하다, 성행하다',
    jp: '盛んだ',
    kana: 'さかんだ',
    ro: 'sakanda',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '盛ん',
      stemro: 'sakan',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '실용적이다',
    jp: '実用的だ',
    kana: 'じつようてきだ',
    ro: 'jitsuyoutekida',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '実用的',
      stemro: 'jitsuyouteki',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '중요하다',
    jp: '重要だ',
    kana: 'じゅうようだ',
    ro: 'juuyouda',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '重要',
      stemro: 'juuyou',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '주요하다',
    jp: '主要だ',
    kana: 'しゅようだ',
    ro: 'shuyouda',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '主要',
      stemro: 'shuyou',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '화려하다',
    jp: '派手だ',
    kana: 'はでだ',
    ro: 'hadeda',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '派手',
      stemro: 'hade',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '불안하다',
    jp: '不安だ',
    kana: 'ふあんだ',
    ro: 'fuanda',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '不安',
      stemro: 'fuan',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '복잡하다',
    jp: '複雑だ',
    kana: 'ふくざつだ',
    ro: 'fukuzatsuda',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '複雑',
      stemro: 'fukuzatsu',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '무사하다',
    jp: '無事だ',
    kana: 'ぶじだ',
    ro: 'bujida',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '無事',
      stemro: 'buji',
    },
  },
  {
    id: '',
    language: 'japanese',
    ko: '훌륭하다',
    jp: '立派だ',
    kana: 'りっぱだ',
    ro: 'rippada',
    type: 'adj',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '立派',
      stemro: 'rippa',
    },
  },
];

export const noun: Word<Noun>[] = [
  {
    language: 'japanese',
    ko: '신호',
    jp: '合図',
    kana: 'あいず',
    ro: 'aizu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '상대방',
    jp: '相手',
    kana: 'あいて',
    ro: 'aite',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '구멍',
    jp: '穴',
    kana: 'あな',
    ro: 'ana',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기름',
    jp: '油',
    kana: 'あぶら',
    ro: 'abura',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '거품',
    jp: '泡',
    kana: 'あわ',
    ro: 'awa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이하',
    jp: '以下',
    kana: 'いか',
    ro: 'ika',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '숨, 호흡',
    jp: '息',
    kana: 'いき',
    ro: 'iki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '목적지, 행선지',
    jp: '行き先',
    kana: 'いきさき',
    ro: 'ikisaki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이후',
    jp: '以降',
    kana: 'いこう',
    ro: 'ikou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '의식',
    jp: '意識',
    kana: 'いしき',
    ro: 'ishiki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '판자, 널빤지',
    jp: '板',
    kana: 'いた',
    ro: 'ita',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '위치',
    jp: '位置',
    kana: 'いち',
    ro: 'ichi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '1초',
    jp: '一秒',
    kana: 'いちびょう',
    ro: 'ichibyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이전',
    jp: '移転',
    kana: 'いてん',
    ro: 'iten',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이동',
    jp: '移動',
    kana: 'いどう',
    ro: 'idou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '인상',
    jp: '印象',
    kana: 'いんしょう',
    ro: 'inshou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '우회전',
    jp: '右折',
    kana: 'うせつ',
    ro: 'usetsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '뒤쪽, 안쪽',
    jp: '裏側',
    kana: 'うらがわ',
    ro: 'uragawa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '영향',
    jp: '影響',
    kana: 'えいきょう',
    ro: 'eikyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '영양',
    jp: '栄養',
    kana: 'えいよう',
    ro: 'eiyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '웃는 얼굴',
    jp: '笑顔',
    kana: 'えがお',
    ro: 'egao',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가지',
    jp: '枝',
    kana: 'えだ',
    ro: 'eda',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '축하',
    jp: 'お祝い',
    kana: 'おいわい',
    ro: 'oiwai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '응원',
    jp: '応援',
    kana: 'おうえん',
    ro: 'ouen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '횡단',
    jp: '横断',
    kana: 'おうだん',
    ro: 'oudan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '왕복',
    jp: '往復',
    kana: 'おうふく',
    ro: 'oufuku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '응모',
    jp: '応募',
    kana: 'おうぼ',
    ro: 'oubo',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '응용',
    jp: '応用',
    kana: 'おうよう',
    ro: 'ouyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '리필',
    jp: 'お代わり',
    kana: 'おかわり',
    ro: 'okawari',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '병문안',
    jp: 'お見舞い',
    kana: 'おみまい',
    ro: 'omimai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '회계, 계산',
    jp: '会計',
    kana: 'かいけい',
    ro: 'kaikei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '개찰',
    jp: '改札',
    kana: 'かいさつ',
    ro: 'kaisatsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '회수',
    jp: '回収',
    kana: 'かいしゅう',
    ro: 'kaishuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '향기',
    jp: '香り',
    kana: 'かおり',
    ro: 'kaori',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '각자',
    jp: '各自',
    kana: 'かくじ',
    ro: 'kakuji',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '각지',
    jp: '各地',
    kana: 'かくち',
    ro: 'kakuchi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '확인',
    jp: '確認',
    kana: 'かくにん',
    ro: 'kakunin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '과거',
    jp: '過去',
    kana: 'かこ',
    ro: 'kako',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '수, 숫자',
    jp: '数',
    kana: 'かず',
    ro: 'kazu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '밑줄',
    jp: '下線',
    kana: 'かせん',
    ro: 'kasen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '어깨',
    jp: '肩',
    kana: 'かた',
    ro: 'kata',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '형태, 모양',
    jp: '形',
    kana: 'かたち',
    ro: 'katachi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '한쪽',
    jp: '片方',
    kana: 'かたほう',
    ro: 'katahou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '편도',
    jp: '片道',
    kana: 'かたみち',
    ro: 'katamichi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가치',
    jp: '価値',
    kana: 'かち',
    ro: 'kachi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '활기',
    jp: '活気',
    kana: 'かっき',
    ro: 'kakki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '활동',
    jp: '活動',
    kana: 'かつどう',
    ro: 'katsudou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가정',
    jp: '仮定',
    kana: 'かてい',
    ro: 'katei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '참음',
    jp: '我慢',
    kana: 'がまん',
    ro: 'gaman',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '껍질, 가죽',
    jp: '皮',
    kana: 'かわ',
    ro: 'kawa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '간격',
    jp: '間隔',
    kana: 'かんかく',
    ro: 'kankaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '감각',
    jp: '感覚',
    kana: 'かんかく',
    ro: 'kankaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '관객',
    jp: '観客',
    kana: 'かんきゃく',
    ro: 'kankyaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '환경',
    jp: '環境',
    kana: 'かんきょう',
    ro: 'kankyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '관계',
    jp: '関係',
    kana: 'かんけい',
    ro: 'kankei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '감격',
    jp: '感激',
    kana: 'かんげき',
    ro: 'kangeki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '관광',
    jp: '観光',
    kana: 'かんこう',
    ro: 'kankou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '관찰',
    jp: '観察',
    kana: 'かんさつ',
    ro: 'kansatsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '관심',
    jp: '関心',
    kana: 'かんしん',
    ro: 'kanshin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '완성',
    jp: '完成',
    kana: 'かんせい',
    ro: 'kansei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기회',
    jp: '機会',
    kana: 'きかい',
    ro: 'kikai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기한',
    jp: '期限',
    kana: 'きげん',
    ro: 'kigen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기술',
    jp: '技術',
    kana: 'ぎじゅつ',
    ro: 'gijutsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '상처',
    jp: '傷',
    kana: 'きず',
    ro: 'kizu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기초',
    jp: '基礎',
    kana: 'きそ',
    ro: 'kiso',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '규칙',
    jp: '規則',
    kana: 'きそく',
    ro: 'kisoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기대',
    jp: '期待',
    kana: 'きたい',
    ro: 'kitai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '귀가',
    jp: '帰宅',
    kana: 'きたく',
    ro: 'kitaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기념',
    jp: '記念',
    kana: 'きねん',
    ro: 'kinen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기본',
    jp: '基本',
    kana: 'きほん',
    ro: 'kihon',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '반대, 거꾸로임',
    jp: '逆',
    kana: 'ぎゃく',
    ro: 'gyaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '휴일',
    jp: '休日',
    kana: 'きゅうじつ',
    ro: 'kyuujitsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '교사',
    jp: '教師',
    kana: 'きょうし',
    ro: 'kyoushi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '공통',
    jp: '共通',
    kana: 'きょうつう',
    ro: 'kyoutsuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '흥미',
    jp: '興味',
    kana: 'きょうみ',
    ro: 'kyoumi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '협력',
    jp: '協力',
    kana: 'きょうりょく',
    ro: 'kyouryoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '거리',
    jp: '距離',
    kana: 'きょり',
    ro: 'kyori',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기록',
    jp: '記録',
    kana: 'きろく',
    ro: 'kiroku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '금연',
    jp: '禁煙',
    kana: 'きんえん',
    ro: "kin'en",
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '금지',
    jp: '禁止',
    kana: 'きんし',
    ro: 'kinshi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '목',
    jp: '首',
    kana: 'くび',
    ro: 'kubi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '고안, 궁리',
    jp: '工夫',
    kana: 'くふう',
    ro: 'kufuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '구분',
    jp: '区分',
    kana: 'くぶん',
    ro: 'kubun',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '구별',
    jp: '区別',
    kana: 'くべつ',
    ro: 'kubetsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '훈련',
    jp: '訓練',
    kana: 'くんれん',
    ro: 'kunren',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '경영',
    jp: '経営',
    kana: 'けいえい',
    ro: 'keiei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '경험',
    jp: '経験',
    kana: 'けいけん',
    ro: 'keiken',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '계산',
    jp: '計算',
    kana: 'けいさん',
    ro: 'keisan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '경유',
    jp: '経由',
    kana: 'けいゆ',
    ro: 'keiyu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '외과',
    jp: '外科',
    kana: 'げか',
    ro: 'geka',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '경치',
    jp: '景色',
    kana: 'けしき',
    ro: 'keshiki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '혈액',
    jp: '血液',
    kana: 'けつえき',
    ro: 'ketsueki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '결석',
    jp: '欠席',
    kana: 'けっせき',
    ro: 'kesseki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '결점',
    jp: '欠点',
    kana: 'けってん',
    ro: 'ketten',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '연기',
    jp: '煙',
    kana: 'けむり',
    ro: 'kemuri',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '원인',
    jp: '原因',
    kana: 'げんいん',
    ro: 'genin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '연구',
    jp: '研究',
    kana: 'けんきゅう',
    ro: 'kenkyuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '검사',
    jp: '検査',
    kana: 'けんさ',
    ro: 'kensa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '현재',
    jp: '現在',
    kana: 'げんざい',
    ro: 'genzai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '감소',
    jp: '減少',
    kana: 'げんしょう',
    ro: 'genshou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '건설',
    jp: '建設',
    kana: 'けんせつ',
    ro: 'kensetsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '구경',
    jp: '見物',
    kana: 'けんぶつ',
    ro: 'kenbutsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '원료',
    jp: '原料',
    kana: 'げんりょう',
    ro: 'genryou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '강연',
    jp: '講演',
    kana: 'こうえん',
    ro: 'kouen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '효과',
    jp: '効果',
    kana: 'こうか',
    ro: 'kouka',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '합계',
    jp: '合計',
    kana: 'ごうけい',
    ro: 'goukei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '교대',
    jp: '交代',
    kana: 'こうたい',
    ro: 'koutai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '교체',
    jp: '交替',
    kana: 'こうたい',
    ro: 'koutai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '행동',
    jp: '行動',
    kana: 'こうどう',
    ro: 'koudou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '교류',
    jp: '交流',
    kana: 'こうりゅう',
    ro: 'kouryuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '얼음',
    jp: '氷',
    kana: 'こおり',
    ro: 'koori',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '호흡',
    jp: '呼吸',
    kana: 'こきゅう',
    ro: 'kokyuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '허리',
    jp: '腰',
    kana: 'こし',
    ro: 'koshi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '고장',
    jp: '故障',
    kana: 'こしょう',
    ro: 'koshou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '개인',
    jp: '個人',
    kana: 'こじん',
    ro: 'kojin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가루',
    jp: '粉',
    kana: 'こな',
    ro: 'kona',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '쌀',
    jp: '米',
    kana: 'こめ',
    ro: 'kome',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '최종',
    jp: '最終',
    kana: 'さいしゅう',
    ro: 'saishuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '최상',
    jp: '最上',
    kana: 'さいじょう',
    ro: 'saijou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '재료',
    jp: '材料',
    kana: 'ざいりょう',
    ro: 'zairyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '비탈길',
    jp: '坂道',
    kana: 'さかみち',
    ro: 'sakamichi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '작업',
    jp: '作業',
    kana: 'さぎょう',
    ro: 'sagyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '작물, 농작물',
    jp: '作物',
    kana: 'さくもつ',
    ro: 'sakumotsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '좌우',
    jp: '左右',
    kana: 'さゆう',
    ro: 'sayuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '참가',
    jp: '参加',
    kana: 'さんか',
    ro: 'sanka',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '찬성',
    jp: '賛成',
    kana: 'さんせい',
    ro: 'sansei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '소금',
    jp: '塩',
    kana: 'しお',
    ro: 'shio',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '지급',
    jp: '支給',
    kana: 'しきゅう',
    ro: 'shikyuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자원',
    jp: '資源',
    kana: 'しげん',
    ro: 'shigen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '사정',
    jp: '事情',
    kana: 'じじょう',
    ro: 'jijou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자신',
    jp: '自信',
    kana: 'じしん',
    ro: 'jishin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자세',
    jp: '姿勢',
    kana: 'しせい',
    ro: 'shisei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자연',
    jp: '自然',
    kana: 'しぜん',
    ro: 'shizen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '준비, 채비',
    jp: '支度',
    kana: 'したく',
    ro: 'shitaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '실업',
    jp: '失業',
    kana: 'しつぎょう',
    ro: 'shitsugyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '실력',
    jp: '実力',
    kana: 'じつりょく',
    ro: 'jitsuryoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '지도',
    jp: '指導',
    kana: 'しどう',
    ro: 'shidou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '마감',
    jp: '締め切り',
    kana: 'しめきり',
    ro: 'shimekiri',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '지면',
    jp: '地面',
    kana: 'じめん',
    ro: 'jimen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '출신 지역, 고장, 현지',
    jp: '地元',
    kana: 'じもと',
    ro: 'jimoto',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '집합',
    jp: '集合',
    kana: 'しゅうごう',
    ro: 'shuugou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '수집',
    jp: '収集',
    kana: 'しゅうしゅう',
    ro: 'shuushuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '정체',
    jp: '渋滞',
    kana: 'じゅうたい',
    ro: 'juutai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '집중',
    jp: '集中',
    kana: 'しゅうちゅう',
    ro: 'shuuchuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '수리',
    jp: '修理',
    kana: 'しゅうり',
    ro: 'shuuri',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '축소',
    jp: '縮小',
    kana: 'しゅくしょう',
    ro: 'shukushou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '수술',
    jp: '手術',
    kana: 'しゅじゅつ',
    ro: 'shujutsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '수단',
    jp: '手段',
    kana: 'しゅだん',
    ro: 'shudan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '주장',
    jp: '主張',
    kana: 'しゅちょう',
    ro: 'shuchou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '출장',
    jp: '出張',
    kana: 'しゅっちょう',
    ro: 'shutchou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '수도',
    jp: '首都',
    kana: 'しゅと',
    ro: 'shuto',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '순번',
    jp: '順番',
    kana: 'じゅんばん',
    ro: 'junban',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '소개',
    jp: '紹介',
    kana: 'しょうかい',
    ro: 'shoukai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '상업',
    jp: '商業',
    kana: 'しょうぎょう',
    ro: 'shougyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조건',
    jp: '条件',
    kana: 'じょうけん',
    ro: 'jouken',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '승차',
    jp: '乗車',
    kana: 'じょうしゃ',
    ro: 'jousha',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '초대',
    jp: '招待',
    kana: 'しょうたい',
    ro: 'shoutai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '소비',
    jp: '消費',
    kana: 'しょうひ',
    ro: 'shouhi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '정보',
    jp: '情報',
    kana: 'じょうほう',
    ro: 'jouhou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '증명',
    jp: '証明',
    kana: 'しょうめい',
    ro: 'shoumei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '정면',
    jp: '正面',
    kana: 'しょうめん',
    ro: 'shoumen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '식물',
    jp: '植物',
    kana: 'しょくぶつ',
    ro: 'shokubutsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '식기',
    jp: '食器',
    kana: 'しょっき',
    ro: 'shokki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자료',
    jp: '資料',
    kana: 'しりょう',
    ro: 'shiryou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '진행',
    jp: '進行',
    kana: 'しんこう',
    ro: 'shinkou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '신청',
    jp: '申請',
    kana: 'しんせい',
    ro: 'shinsei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '진보',
    jp: '進歩',
    kana: 'しんぽ',
    ro: 'shinpo',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '숫자',
    jp: '数字',
    kana: 'すうじ',
    ro: 'suuji',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '두통',
    jp: '頭痛',
    kana: 'ずつう',
    ro: 'zutsuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '모래',
    jp: '砂',
    kana: 'すな',
    ro: 'suna',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '정답',
    jp: '正解',
    kana: 'せいかい',
    ro: 'seikai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '성격',
    jp: '性格',
    kana: 'せいかく',
    ro: 'seikaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '제한',
    jp: '制限',
    kana: 'せいげん',
    ro: 'seigen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '성공',
    jp: '成功',
    kana: 'せいこう',
    ro: 'seikou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '정상',
    jp: '正常',
    kana: 'せいじょう',
    ro: 'seijou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '성적',
    jp: '成績',
    kana: 'せいせき',
    ro: 'seiseki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '정리',
    jp: '整理',
    kana: 'せいり',
    ro: 'seiri',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '석유',
    jp: '石油',
    kana: 'せきゆ',
    ro: 'sekiyu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '선수',
    jp: '選手',
    kana: 'せんしゅ',
    ro: 'senshu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '세탁',
    jp: '洗濯',
    kana: 'せんたく',
    ro: 'sentaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '선전',
    jp: '宣伝',
    kana: 'せんでん',
    ro: 'senden',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '전문',
    jp: '専門',
    kana: 'せんもん',
    ro: 'senmon',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '상상',
    jp: '想像',
    kana: 'そうぞう',
    ro: 'souzou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조퇴',
    jp: '早退',
    kana: 'そうたい',
    ro: 'soutai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '상담',
    jp: '相談',
    kana: 'そうだん',
    ro: 'soudan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '속도',
    jp: '速度',
    kana: 'そくど',
    ro: 'sokudo',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '바닥',
    jp: '底',
    kana: 'そこ',
    ro: 'soko',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '졸업',
    jp: '卒業',
    kana: 'そつぎょう',
    ro: 'sotsugyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '존재',
    jp: '存在',
    kana: 'そんざい',
    ro: 'sonzai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '대회',
    jp: '大会',
    kana: 'たいかい',
    ro: 'taikai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '대금',
    jp: '代金',
    kana: 'だいきん',
    ro: 'daikin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '체재',
    jp: '滞在',
    kana: 'たいざい',
    ro: 'taizai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '부엌',
    jp: '台所',
    kana: 'だいどころ',
    ro: 'daidokoro',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '태풍',
    jp: '台風',
    kana: 'たいふう',
    ro: 'taifuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '체력',
    jp: '体力',
    kana: 'たいりょく',
    ro: 'tairyoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '타인',
    jp: '他人',
    kana: 'たにん',
    ro: 'tanin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '탄생',
    jp: '誕生',
    kana: 'たんじょう',
    ro: 'tanjou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '단체',
    jp: '団体',
    kana: 'だんたい',
    ro: 'dantai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '지각',
    jp: '遅刻',
    kana: 'ちこく',
    ro: 'chikoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '중고',
    jp: '中古',
    kana: 'ちゅうこ',
    ro: 'chuuko',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '주차',
    jp: '駐車',
    kana: 'ちゅうしゃ',
    ro: 'chuusha',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '상태',
    jp: '調子',
    kana: 'ちょうし',
    ro: 'choushi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조식',
    jp: '朝食',
    kana: 'ちょうしょく',
    ro: 'choushoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '직접',
    jp: '直接',
    kana: 'ちょくせつ',
    ro: 'chokusetsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '통근',
    jp: '通勤',
    kana: 'つうきん',
    ro: 'tsuukin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '통역',
    jp: '通訳',
    kana: 'つうやく',
    ro: 'tsuuyaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '사정, 형편',
    jp: '都合',
    kana: 'つごう',
    ro: 'tsugou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '정전',
    jp: '停電',
    kana: 'ていでん',
    ro: 'teiden',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '전언',
    jp: '伝言',
    kana: 'でんごん',
    ro: 'dengon',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '천장',
    jp: '天井',
    kana: 'てんじょう',
    ro: 'tenjou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '동작',
    jp: '動作',
    kana: 'どうさ',
    ro: 'dousa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '당일',
    jp: '当日',
    kana: 'とうじつ',
    ro: 'toujitsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '등장',
    jp: '登場',
    kana: 'とうじょう',
    ro: 'toujou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '도착',
    jp: '到着',
    kana: 'とうちゃく',
    ro: 'touchaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '등록',
    jp: '登録',
    kana: 'とうろく',
    ro: 'touroku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '독신',
    jp: '独身',
    kana: 'どくしん',
    ro: 'dokushin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '특징',
    jp: '特徴',
    kana: 'とくちょう',
    ro: 'tokuchou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '독립',
    jp: '独立',
    kana: 'どくりつ',
    ro: 'dokuritsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '등산',
    jp: '登山',
    kana: 'とざん',
    ro: 'tozan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '도중',
    jp: '途中',
    kana: 'とちゅう',
    ro: 'tochuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '노력',
    jp: '努力',
    kana: 'どりょく',
    ro: 'doryoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '비밀',
    jp: '内緒',
    kana: 'ないしょ',
    ro: 'naisho',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '내용',
    jp: '内容',
    kana: 'ないよう',
    ro: 'naiyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '속, 알맹이',
    jp: '中身',
    kana: 'なかみ',
    ro: 'nakami',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '파도',
    jp: '波',
    kana: 'なみ',
    ro: 'nami',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '눈물',
    jp: '涙',
    kana: 'なみだ',
    ro: 'namida',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '짐',
    jp: '荷物',
    kana: 'にもつ',
    ro: 'nimotsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '인간',
    jp: '人間',
    kana: 'にんげん',
    ro: 'ningen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가격',
    jp: '値段',
    kana: 'ねだん',
    ro: 'nedan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '뿌리',
    jp: '根',
    kana: 'ね',
    ro: 'ne',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '연중',
    jp: '年中',
    kana: 'ねんじゅう',
    ro: 'nenjuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '농업',
    jp: '農業',
    kana: 'のうぎょう',
    ro: 'nougyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이, 치아',
    jp: '歯',
    kana: 'は',
    ro: 'ha',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '잎',
    jp: '葉',
    kana: 'は',
    ro: 'ha',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '~배',
    jp: '～倍',
    kana: '～ばい',
    ro: 'bai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '발생',
    jp: '発生',
    kana: 'はっせい',
    ro: 'hassei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '발전',
    jp: '発展',
    kana: 'はってん',
    ro: 'hatten',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '발표',
    jp: '発表',
    kana: 'はっぴょう',
    ro: 'happyou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '반대',
    jp: '反対',
    kana: 'はんたい',
    ro: 'hantai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '비교',
    jp: '比較',
    kana: 'ひかく',
    ro: 'hikaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '부정',
    jp: '否定',
    kana: 'ひてい',
    ro: 'hitei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '표시',
    jp: '表示',
    kana: 'ひょうじ',
    ro: 'hyouji',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '표면',
    jp: '表面',
    kana: 'ひょうめん',
    ro: 'hyoumen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '풍경',
    jp: '風景',
    kana: 'ふうけい',
    ro: 'fuukei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '복수',
    jp: '複数',
    kana: 'ふくすう',
    ro: 'fukusuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '물가',
    jp: '物価',
    kana: 'ぶっか',
    ro: 'bukka',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '비등, 물이 끓음',
    jp: '沸騰',
    kana: 'ふっとう',
    ro: 'futtou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이불',
    jp: '布団',
    kana: 'ふとん',
    ro: 'futon',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '부분',
    jp: '部分',
    kana: 'ぶぶん',
    ro: 'bubun',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '문장',
    jp: '文章',
    kana: 'ぶんしょう',
    ro: 'bunshou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '분류',
    jp: '分類',
    kana: 'ぶんるい',
    ro: 'bunrui',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '평균',
    jp: '平均',
    kana: 'へいきん',
    ro: 'heikin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '변화',
    jp: '変化',
    kana: 'へんか',
    ro: 'henka',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '무역',
    jp: '貿易',
    kana: 'ぼうえき',
    ro: 'boueki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '방향',
    jp: '方向',
    kana: 'ほうこう',
    ro: 'houkou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '방법',
    jp: '方法',
    kana: 'ほうほう',
    ro: 'houhou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '방문',
    jp: '訪問',
    kana: 'ほうもん',
    ro: 'houmon',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '법률',
    jp: '法律',
    kana: 'ほうりつ',
    ro: 'houritsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '모집',
    jp: '募集',
    kana: 'ぼしゅう',
    ro: 'boshuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '손자',
    jp: '孫',
    kana: 'まご',
    ro: 'mago',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '콩',
    jp: '豆',
    kana: 'まめ',
    ro: 'mame',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '만족',
    jp: '満足',
    kana: 'まんぞく',
    ro: 'manzoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '호수',
    jp: '湖',
    kana: 'みずうみ',
    ro: 'mizuumi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '녹색, 초록',
    jp: '緑',
    kana: 'みどり',
    ro: 'midori',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '미래',
    jp: '未来',
    kana: 'みらい',
    ro: 'mirai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '명령',
    jp: '命令',
    kana: 'めいれい',
    ro: 'meirei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '면허',
    jp: '免許',
    kana: 'めんきょ',
    ro: 'menkyo',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '면접',
    jp: '面接',
    kana: 'めんせつ',
    ro: 'mensetsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '목적',
    jp: '目的',
    kana: 'もくてき',
    ro: 'mokuteki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '문자',
    jp: '文字',
    kana: 'もじ',
    ro: 'moji',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '숲',
    jp: '森',
    kana: 'もり',
    ro: 'mori',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '불평, 불만',
    jp: '文句',
    kana: 'もんく',
    ro: 'monku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '지붕',
    jp: '屋根',
    kana: 'やね',
    ro: 'yane',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '마루',
    jp: '床',
    kana: 'ゆか',
    ro: 'yuka',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '수출',
    jp: '輸出',
    kana: 'ゆしゅつ',
    ro: 'yushutsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '수입',
    jp: '輸入',
    kana: 'ゆにゅう',
    ro: 'yunyuu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '용기',
    jp: '容器',
    kana: 'ようき',
    ro: 'youki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '옆',
    jp: '横',
    kana: 'よこ',
    ro: 'yoko',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '더러움, 오염',
    jp: '汚れ',
    kana: 'よごれ',
    ro: 'yogore',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '예측',
    jp: '予測',
    kana: 'よそく',
    ro: 'yosoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '밤중',
    jp: '夜中',
    kana: 'よなか',
    ro: 'yonaka',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '예방',
    jp: '予防',
    kana: 'よぼう',
    ro: 'yobou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '부재(중)',
    jp: '留守',
    kana: 'るす',
    ro: 'rusu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '열, 줄',
    jp: '列',
    kana: 'れつ',
    ro: 'retsu',
    type: 'noun',
    example: [],
  },
];

export const good: Word<Verb>[] = [
  {
    ko: '질리다, 싫증나다',
    jp: '飽きる',
    kana: 'あきる',
    ro: 'akiru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '飽き',
      stemro: 'aki',
    },
  },
  {
    ko: '맞다, 적중하다',
    jp: '当たる',
    kana: 'あたる',
    ro: 'ataru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '当た',
      stemro: 'ata',
    },
  },
  {
    ko: '남다',
    jp: '余る',
    kana: 'あまる',
    ro: 'amaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '余ま',
      stemro: 'ama',
    },
  },
  {
    ko: '(스웨터를) 짜다',
    jp: '編む',
    kana: 'あむ',
    ro: 'amu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '編',
      stemro: 'a',
    },
  },
  {
    ko: '나타내다, 표현하다',
    jp: '表す',
    kana: 'あらわす',
    ro: 'arawasu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '表わ',
      stemro: 'arawa',
    },
  },
  {
    ko: '허둥대다',
    jp: '慌てる',
    kana: 'あわてる',
    ro: 'awateru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '慌て',
      stemro: 'awate',
    },
  },
  {
    ko: '서두르다',
    jp: '急ぐ',
    kana: 'いそぐ',
    ro: 'isogu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'ぐ',
      endingro: 'gu',
      exception: false,
      form: 1,
      stemjp: '急',
      stemro: 'iso',
    },
  },
  {
    ko: '도전하다',
    jp: '挑む',
    kana: 'いどむ',
    ro: 'idomu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '挑',
      stemro: 'i',
    },
  },
  {
    ko: '심다',
    jp: '植える',
    kana: 'うえる',
    ro: 'ueru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '植え',
      stemro: 'ue',
    },
  },
  {
    ko: '수취하다, 받다',
    jp: '受け取る',
    kana: 'うけとる',
    ro: 'uketoru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '受け取',
      stemro: 'uketo',
    },
  },
  {
    ko: '의심하다',
    jp: '疑う',
    kana: 'うたがう',
    ro: 'utagau',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '疑たが',
      stemro: 'utaga',
    },
  },
  {
    ko: '치다',
    jp: '打つ',
    kana: 'うつ',
    ro: 'utsu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'つ',
      endingro: 'tsu',
      exception: false,
      form: 1,
      stemjp: '打',
      stemro: 'u',
    },
  },
  {
    ko: '옮다, 이동하다',
    jp: '移る',
    kana: 'うつる',
    ro: 'utsuru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '移つ',
      stemro: 'utsu',
    },
  },
  {
    ko: '빼앗다',
    jp: '奪う',
    kana: 'うばう',
    ro: 'ubau',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '奪ば',
      stemro: 'uba',
    },
  },
  {
    ko: '묻다, 메우다, 채우다',
    jp: '埋める',
    kana: 'うめる',
    ro: 'umeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '埋め',
      stemro: 'ume',
    },
  },
  {
    ko: '다 팔리다, 매진되다',
    jp: '売り切れる',
    kana: 'うりきれる',
    ro: 'urikireru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '売り切れ',
      stemro: 'urikire',
    },
  },
  {
    ko: '따라잡다',
    jp: '追いつく',
    kana: 'おいつく',
    ro: 'oitsuku',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '追いつ',
      stemro: 'oitsu',
    },
  },
  {
    ko: '억제하다, 줄이다',
    jp: '抑える',
    kana: 'おさえる',
    ro: 'osaeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '抑え',
      stemro: 'osae',
    },
  },
  {
    ko: '누르다, 밀다',
    jp: '押す',
    kana: 'おす',
    ro: 'osu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '押',
      stemro: 'o',
    },
  },
  {
    ko: '침착하다, 차분해지다',
    jp: '落ち着く',
    kana: 'おちつく',
    ro: 'ochitsuku',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '落ち着',
      stemro: 'ochitsu',
    },
  },
  {
    ko: '놀라다',
    jp: '驚く',
    kana: 'おどろく',
    ro: 'odoroku',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '驚ろ',
      stemro: 'odoro',
    },
  },
  {
    ko: '외우다, 기억하다',
    jp: '覚える',
    kana: 'おぼえる',
    ro: 'oboeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '覚え',
      stemro: 'oboe',
    },
  },
  {
    ko: '꺾다, 접다',
    jp: '折る',
    kana: 'おる',
    ro: 'oru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '折',
      stemro: 'o',
    },
  },
  {
    ko: '꺾이다, 접히다',
    jp: '折れる',
    kana: 'おれる',
    ro: 'oreru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '折れ',
      stemro: 'ore',
    },
  },
  {
    ko: '바꾸다, 교환하다',
    jp: '替える',
    kana: 'かえる',
    ro: 'kaeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '替え',
      stemro: 'kae',
    },
  },
  {
    ko: '빛나다',
    jp: '輝く',
    kana: 'かがやく',
    ro: 'kagayaku',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '輝や',
      stemro: 'kagaya',
    },
  },
  {
    ko: '숨기다',
    jp: '隠す',
    kana: 'かくす',
    ro: 'kakusu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '隠',
      stemro: 'kaku',
    },
  },
  {
    ko: '전속력으로 달리다, 뛰다',
    jp: '駆ける',
    kana: 'かける',
    ro: 'kakeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '駆け',
      stemro: 'kake',
    },
  },
  {
    ko: '둘러싸다',
    jp: '囲む',
    kana: 'かこむ',
    ro: 'kakomu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '囲こ',
      stemro: 'kako',
    },
  },
  {
    ko: '겹치다, 포개다, 거듭하다',
    jp: '重ねる',
    kana: 'かさねる',
    ro: 'kasaneru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '重ね',
      stemro: 'kasane',
    },
  },
  {
    ko: '장식하다',
    jp: '飾る',
    kana: 'かざる',
    ro: 'kazaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '飾',
      stemro: 'kaza',
    },
  },
  {
    ko: '빌려주다',
    jp: '貸す',
    kana: 'かす',
    ro: 'kasu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '貸',
      stemro: 'ka',
    },
  },
  {
    ko: '빌리다',
    jp: '借りる',
    kana: 'かりる',
    ro: 'kariru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '借り',
      stemro: 'kari',
    },
  },
  {
    ko: '시들다',
    jp: '枯れる',
    kana: 'かれる',
    ro: 'kareru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '枯れ',
      stemro: 'kare',
    },
  },
  {
    ko: '마르다, 건조되다',
    jp: '乾く',
    kana: 'かわく',
    ro: 'kawaku',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '乾わ',
      stemro: 'kawa',
    },
  },
  {
    ko: '꺼지다, 사라지다',
    jp: '消える',
    kana: 'きえる',
    ro: 'kieru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '消え',
      stemro: 'kie',
    },
  },
  {
    ko: '싫어하다',
    jp: '嫌う',
    kana: 'きらう',
    ro: 'kirau',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '嫌ら',
      stemro: 'kira',
    },
  },
  {
    ko: '나눠주다',
    jp: '配る',
    kana: 'くばる',
    ro: 'kubaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '配ば',
      stemro: 'kuba',
    },
  },
  {
    ko: '조립하다',
    jp: '組み立てる',
    kana: 'くみたてる',
    ro: 'kumitateru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '組み立て',
      stemro: 'kumitate',
    },
  },
  {
    ko: '짜다, 끼다',
    jp: '組む',
    kana: 'くむ',
    ro: 'kumu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '組',
      stemro: 'ku',
    },
  },
  {
    ko: '반복하다',
    jp: '繰り返す',
    kana: 'くりかえす',
    ro: 'kurikaesu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '繰り返',
      stemro: 'kurikae',
    },
  },
  {
    ko: '더하다, 추가하다',
    jp: '加える',
    kana: 'くわえる',
    ro: 'kuwaeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '加え',
      stemro: 'kuwae',
    },
  },
  {
    ko: '얼다',
    jp: '凍る',
    kana: 'こおる',
    ro: 'kooru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '凍',
      stemro: 'koo',
    },
  },
  {
    ko: '(음식이) 타다, 눌러붙다',
    jp: '焦げる',
    kana: 'こげる',
    ro: 'kogeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '焦げ',
      stemro: 'koge',
    },
  },
  {
    ko: '거절하다',
    jp: '断る',
    kana: 'ことわる',
    ro: 'kotowaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '断わ',
      stemro: 'koto',
    },
  },
  {
    ko: '구르다, 넘어지다',
    jp: '転ぶ',
    kana: 'ころぶ',
    ro: 'korobu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'ぶ',
      endingro: 'bu',
      exception: false,
      form: 1,
      stemjp: '転',
      stemro: 'koro',
    },
  },
  {
    ko: '무서워하다',
    jp: '怖がる',
    kana: 'こわがる',
    ro: 'kowagaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '怖が',
      stemro: 'kowaga',
    },
  },
  {
    ko: '(눈이) 떠지다',
    jp: '覚める',
    kana: 'さめる',
    ro: 'sameru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '覚め',
      stemro: 'same',
    },
  },
  {
    ko: '떠들다, 소란 피우다',
    jp: '騒ぐ',
    kana: 'さわぐ',
    ro: 'sawagu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'ぐ',
      endingro: 'gu',
      exception: false,
      form: 1,
      stemjp: '騒',
      stemro: 'sawa',
    },
  },
  {
    ko: '만지다',
    jp: '触る',
    kana: 'さわる',
    ro: 'sawaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '触',
      stemro: 'sawa',
    },
  },
  {
    ko: '가라앉다',
    jp: '沈む',
    kana: 'しずむ',
    ro: 'shizumu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '沈',
      stemro: 'shizu',
    },
  },
  {
    ko: '따르다',
    jp: '従う',
    kana: 'したがう',
    ro: 'shitagau',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '従が',
      stemro: 'shitaga',
    },
  },
  {
    ko: '(끈으로) 묶다',
    jp: '縛る',
    kana: 'しばる',
    ro: 'shibaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '縛',
      stemro: 'shiba',
    },
  },
  {
    ko: '짜다, 줄이다',
    jp: '絞る',
    kana: 'しぼる',
    ro: 'shiboru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '絞',
      stemro: 'shibo',
    },
  },
  {
    ko: '나타내다, 제시하다',
    jp: '示す',
    kana: 'しめす',
    ro: 'shimesu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '示',
      stemro: 'shime',
    },
  },
  {
    ko: '바싹 졸라 메다',
    jp: '締める',
    kana: 'しめる',
    ro: 'shimeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '締め',
      stemro: 'shime',
    },
  },
  {
    ko: '지나다',
    jp: '過ぎる',
    kana: 'すぎる',
    ro: 'sugiru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: true,
      form: 2,
      stemjp: '過ぎ',
      stemro: 'sugi',
    },
  },
  {
    ko: '버리다',
    jp: '捨てる',
    kana: 'すてる',
    ro: 'suteru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '捨て',
      stemro: 'sute',
    },
  },
  {
    ko: '쓰러지다, 넘어지다',
    jp: '倒れる',
    kana: 'たおれる',
    ro: 'taoreru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '倒れ',
      stemro: 'taore',
    },
  },
  {
    ko: '확인하다',
    jp: '確かめる',
    kana: 'たしかめる',
    ro: 'tashikameru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '確かめ',
      stemro: 'tashikame',
    },
  },
  {
    ko: '싸우다',
    jp: '戦う',
    kana: 'たたかう',
    ro: 'tatakau',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '戦たか',
      stemro: 'tataka',
    },
  },
  {
    ko: '개다',
    jp: '畳む',
    kana: 'たたむ',
    ro: 'tatamu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '畳',
      stemro: 'tata',
    },
  },
  {
    ko: '(시간이) 흐르다',
    jp: '経つ',
    kana: 'たつ',
    ro: 'tatsu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'つ',
      endingro: 'tsu',
      exception: false,
      form: 1,
      stemjp: '経',
      stemro: 'ta',
    },
  },
  {
    ko: '입 다물다',
    jp: '黙る',
    kana: 'だまる',
    ro: 'damaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '黙',
      stemro: 'dama',
    },
  },
  {
    ko: '의지하다, 기대다',
    jp: '頼る',
    kana: 'たよる',
    ro: 'tayoru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '頼',
      stemro: 'tayo',
    },
  },
  {
    ko: '다르다',
    jp: '違う',
    kana: 'ちがう',
    ro: 'chigau',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '違が',
      stemro: 'chiga',
    },
  },
  {
    ko: '피곤하다',
    jp: '疲れる',
    kana: 'つかれる',
    ro: 'tsukareru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '疲れ',
      stemro: 'tsukare',
    },
  },
  {
    ko: '전해지다',
    jp: '伝わる',
    kana: 'つたわる',
    ro: 'tsutawaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '伝わ',
      stemro: 'tsuta',
    },
  },
  {
    ko: '싸다, 포장하다',
    jp: '包む',
    kana: 'つつむ',
    ro: 'tsutsumu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '包',
      stemro: 'tsutsu',
    },
  },
  {
    ko: '근무하다',
    jp: '勤める',
    kana: 'つとめる',
    ro: 'tsutomeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '勤め',
      stemro: 'tsutome',
    },
  },
  {
    ko: '통과하다, 지나가다',
    jp: '通る',
    kana: 'とおる',
    ro: 'tooru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '通',
      stemro: 'too',
    },
  },
  {
    ko: '(문제가) 풀리다, 해결되다',
    jp: '解ける',
    kana: 'とける',
    ro: 'tokeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '解け',
      stemro: 'toke',
    },
  },
  {
    ko: '녹다',
    jp: '溶ける',
    kana: 'とける',
    ro: 'tokeru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '溶け',
      stemro: 'toke',
    },
  },
  {
    ko: '(눈을) 감다, 덮다',
    jp: '閉じる',
    kana: 'とじる',
    ro: 'tojiru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: true,
      form: 2,
      stemjp: '閉じ',
      stemro: 'toji',
    },
  },
  {
    ko: '고함치다, 호통치다',
    jp: '怒鳴る',
    kana: 'どなる',
    ro: 'donaru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '怒鳴',
      stemro: 'dona',
    },
  },
  {
    ko: '취소하다',
    jp: '取り消す',
    kana: 'とりけす',
    ro: 'torikesu',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '取り消',
      stemro: 'torike',
    },
  },
  {
    ko: '흐르다',
    jp: '流れる',
    kana: 'ながれる',
    ro: 'nagareru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '流れ',
      stemro: 'nagare',
    },
  },
  {
    ko: '위로하다',
    jp: '慰める',
    kana: 'なぐさめる',
    ro: 'nagusameru',
    type: 'verb',
    language: 'japanese',
    id: '',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '慰さめ',
      stemro: 'nagusame',
    },
  },
];

export const hiragana = {
  a: [
    { jp: 'あ', ro: 'a', ko: '아' },
    { jp: 'い', ro: 'i', ko: '이' },
    { jp: 'う', ro: 'u', ko: '우' },
    { jp: 'え', ro: 'e', ko: '에' },
    { jp: 'お', ro: 'o', ko: '오' },
  ],
  ka: [
    { jp: 'か', ro: 'ka', ko: '카' },
    { jp: 'き', ro: 'ki', ko: '키' },
    { jp: 'く', ro: 'ku', ko: '쿠' },
    { jp: 'け', ro: 'ke', ko: '케' },
    { jp: 'こ', ro: 'ko', ko: '코' },
  ],
  sa: [
    { jp: 'さ', ro: 'sa', ko: '사' },
    { jp: 'し', ro: 'shi', ko: '시' },
    { jp: 'す', ro: 'su', ko: '스' },
    { jp: 'せ', ro: 'se', ko: '세' },
    { jp: 'そ', ro: 'so', ko: '소' },
    { jp: 'しゃ', ro: 'sha', ko: '샤' },
    { jp: 'しゅ', ro: 'shu', ko: '슈' },
    { jp: 'しょ', ro: 'sho', ko: '쇼' },
  ],
  ta: [
    { jp: 'た', ro: 'ta', ko: '타' },
    { jp: 'ち', ro: 'chi', ko: '치' },
    { jp: 'つ', ro: 'tsu', ko: '츠' },
    { jp: 'っ', ro: 't', ko: '츠' },
    { jp: 'て', ro: 'te', ko: '테' },
    { jp: 'と', ro: 'to', ko: '토' },
  ],
  na: [
    { jp: 'な', ro: 'na', ko: '나' },
    { jp: 'に', ro: 'ni', ko: '니' },
    { jp: 'ぬ', ro: 'nu', ko: '누' },
    { jp: 'ね', ro: 'ne', ko: '네' },
    { jp: 'の', ro: 'no', ko: '노' },
  ],
  ha: [
    { jp: 'は', ro: 'ha', ko: '하' },
    { jp: 'ひ', ro: 'hi', ko: '히' },
    { jp: 'ふ', ro: 'fu', ko: '후' },
    { jp: 'へ', ro: 'he', ko: '헤' },
    { jp: 'ほ', ro: 'ho', ko: '호' },
  ],
  ma: [
    { jp: 'ま', ro: 'ma', ko: '마' },
    { jp: 'み', ro: 'mi', ko: '미' },
    { jp: 'む', ro: 'mu', ko: '무' },
    { jp: 'め', ro: 'me', ko: '메' },
    { jp: 'も', ro: 'mo', ko: '모' },
  ],
  ya: [
    { jp: 'や', ro: 'ya', ko: '야' },
    { jp: 'ゆ', ro: 'yu', ko: '유' },
    { jp: 'よ', ro: 'yo', ko: '요' },
    // { jp: 'ょ', ro: 'yo', ko: '요' },
  ],
  ra: [
    { jp: 'ら', ro: 'ra', ko: '라' },
    { jp: 'り', ro: 'ri', ko: '리' },
    { jp: 'る', ro: 'ru', ko: '루' },
    { jp: 'れ', ro: 're', ko: '레' },
    { jp: 'ろ', ro: 'ro', ko: '로' },
  ],
  wa: [
    { jp: 'わ', ro: 'wa', ko: '와' },
    { jp: 'を', ro: 'wo', ko: '오' },
    { jp: 'ん', ro: 'n', ko: '은/는' },
  ],
  ga: [
    { jp: 'が', ro: 'ga', ko: '가' },
    { jp: 'ぎ', ro: 'gi', ko: '기' },
    { jp: 'ぐ', ro: 'gu', ko: '구' },
    { jp: 'げ', ro: 'ge', ko: '게' },
    { jp: 'ご', ro: 'go', ko: '고' },
  ],
  za: [
    { jp: 'ざ', ro: 'za', ko: '자' },
    { jp: 'じ', ro: 'ji', ko: '지' },
    { jp: 'ず', ro: 'zu', ko: '즈' },
    { jp: 'ぜ', ro: 'ze', ko: '제' },
    { jp: 'ぞ', ro: 'zo', ko: '조' },
  ],
  da: [
    { jp: 'だ', ro: 'da', ko: '다' },
    { jp: 'ぢ', ro: 'ji', ko: '지' },
    { jp: 'づ', ro: 'zu', ko: '즈' },
    { jp: 'で', ro: 'de', ko: '데' },
    { jp: 'ど', ro: 'do', ko: '도' },
  ],
  ba: [
    { jp: 'ば', ro: 'ba', ko: '바' },
    { jp: 'び', ro: 'bi', ko: '비' },
    { jp: 'ぶ', ro: 'bu', ko: '부' },
    { jp: 'べ', ro: 'be', ko: '베' },
    { jp: 'ぼ', ro: 'bo', ko: '보' },
  ],
  pa: [
    { jp: 'ぱ', ro: 'pa', ko: '파' },
    { jp: 'ぴ', ro: 'pi', ko: '피' },
    { jp: 'ぷ', ro: 'pu', ko: '푸' },
    { jp: 'ぺ', ro: 'pe', ko: '페' },
    { jp: 'ぽ', ro: 'po', ko: '포' },
  ],
};

export const katakana = {
  a: [
    { jp: 'ア', ro: 'a', ko: '아' },
    { jp: 'イ', ro: 'i', ko: '이' },
    { jp: 'ウ', ro: 'u', ko: '우' },
    { jp: 'エ', ro: 'e', ko: '에' },
    { jp: 'オ', ro: 'o', ko: '오' },
  ],
  ka: [
    { jp: 'カ', ro: 'ka', ko: '카' },
    { jp: 'キ', ro: 'ki', ko: '키' },
    { jp: 'ク', ro: 'ku', ko: '쿠' },
    { jp: 'ケ', ro: 'ke', ko: '케' },
    { jp: 'コ', ro: 'ko', ko: '코' },
  ],
  sa: [
    { jp: 'サ', ro: 'sa', ko: '사' },
    { jp: 'シ', ro: 'shi', ko: '시' },
    { jp: 'ス', ro: 'su', ko: '스' },
    { jp: 'セ', ro: 'se', ko: '세' },
    { jp: 'ソ', ro: 'so', ko: '소' },
  ],
  ta: [
    { jp: 'タ', ro: 'ta', ko: '타' },
    { jp: 'チ', ro: 'chi', ko: '치' },
    { jp: 'ツ', ro: 'tsu', ko: '츠' },
    { jp: 'テ', ro: 'te', ko: '테' },
    { jp: 'ト', ro: 'to', ko: '토' },
  ],
  na: [
    { jp: 'ナ', ro: 'na', ko: '나' },
    { jp: 'ニ', ro: 'ni', ko: '니' },
    { jp: 'ヌ', ro: 'nu', ko: '누' },
    { jp: 'ネ', ro: 'ne', ko: '네' },
    { jp: 'ノ', ro: 'no', ko: '노' },
  ],
  ha: [
    { jp: 'ハ', ro: 'ha', ko: '하' },
    { jp: 'ヒ', ro: 'hi', ko: '히' },
    { jp: 'フ', ro: 'fu', ko: '후' },
    { jp: 'ヘ', ro: 'he', ko: '헤' },
    { jp: 'ホ', ro: 'ho', ko: '호' },
  ],
  ma: [
    { jp: 'マ', ro: 'ma', ko: '마' },
    { jp: 'ミ', ro: 'mi', ko: '미' },
    { jp: 'ム', ro: 'mu', ko: '무' },
    { jp: 'メ', ro: 'me', ko: '메' },
    { jp: 'モ', ro: 'mo', ko: '모' },
  ],
  ya: [
    { jp: 'ヤ', ro: 'ya', ko: '야' },
    { jp: 'ユ', ro: 'yu', ko: '유' },
    { jp: 'ヨ', ro: 'yo', ko: '요' },
  ],
  ra: [
    { jp: 'ラ', ro: 'ra', ko: '라' },
    { jp: 'リ', ro: 'ri', ko: '리' },
    { jp: 'ル', ro: 'ru', ko: '루' },
    { jp: 'レ', ro: 're', ko: '레' },
    { jp: 'ロ', ro: 'ro', ko: '로' },
  ],
  wa: [
    { jp: 'ワ', ro: 'wa', ko: '와' },
    { jp: 'ヲ', ro: 'wo', ko: '오' },
    { jp: 'ン', ro: 'n', ko: '은/는' },
  ],
  ga: [
    { jp: 'ガ', ro: 'ga', ko: '가' },
    { jp: 'ギ', ro: 'gi', ko: '기' },
    { jp: 'グ', ro: 'gu', ko: '구' },
    { jp: 'ゲ', ro: 'ge', ko: '게' },
    { jp: 'ゴ', ro: 'go', ko: '고' },
  ],
  za: [
    { jp: 'ザ', ro: 'za', ko: '자' },
    { jp: 'ジ', ro: 'ji', ko: '지' },
    { jp: 'ズ', ro: 'zu', ko: '즈' },
    { jp: 'ゼ', ro: 'ze', ko: '제' },
    { jp: 'ゾ', ro: 'zo', ko: '조' },
  ],
  da: [
    { jp: 'ダ', ro: 'da', ko: '다' },
    { jp: 'ヂ', ro: 'ji', ko: '지' },
    { jp: 'ヅ', ro: 'zu', ko: '즈' },
    { jp: 'デ', ro: 'de', ko: '데' },
    { jp: 'ド', ro: 'do', ko: '도' },
  ],
  ba: [
    { jp: 'バ', ro: 'ba', ko: '바' },
    { jp: 'ビ', ro: 'bi', ko: '비' },
    { jp: 'ブ', ro: 'bu', ko: '부' },
    { jp: 'ベ', ro: 'be', ko: '베' },
    { jp: 'ボ', ro: 'bo', ko: '보' },
  ],
  pa: [
    { jp: 'パ', ro: 'pa', ko: '파' },
    { jp: 'ピ', ro: 'pi', ko: '피' },
    { jp: 'プ', ro: 'pu', ko: '푸' },
    { jp: 'ペ', ro: 'pe', ko: '페' },
    { jp: 'ポ', ro: 'po', ko: '포' },
  ],
};

// export const onConvert = (data: Verb) => {
//   const _logic: any = logic.find(({ type = '' }) => type === 'present');

//   const { form = 0, endingro = '', stemjp = '' } = data;

//   const good = _logic['value'][form];
//   const a = good[endingro];

//   const romaji = _logic['value'][form][endingro].split('_');

//   let result = '';
//   romaji.map((o: string) => {
//     Object.values(hiragana).forEach((data) => {
//       const { jp = '' } = data.find(({ ro: _ro }) => _ro === o) || {};
//       if (jp) result += jp;
//     });
//   });
//   return result;
// };
