export interface Verb {
  stemjp: string;
  stemro: string;
  endingjp: string;
  endingro: string;
  form?: number;
  exception: boolean;
}

export interface Noun {
  ko: string;
  jp: string;
}

export interface Example {
  jp: string;
  ko: string;
}

export interface Adverb {}

export interface Word<T> {
  id?: string;
  ko: string;
  jp: string;
  kana: string;
  ro: string;
  type: 'verb' | 'noun' | 'adv' | 'adj';
  language: string;
  etc?: T;
  example?: Example[];
}

export const typeGbn = {
  verb: '동사',
  noun: '명사',
  adv: '부사',
  adj: '형용사',
};

export const adv = [
  {
    language: 'japanese',
    ko: '곧',
    jp: 'すぐ',
    kana: 'すぐ',
    ro: 'sugu',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '항상',
    jp: 'いつも',
    kana: 'いつも',
    ro: 'itsumo',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '많이',
    jp: 'たくさん',
    kana: 'たくさん',
    ro: 'takusan',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '매우',
    jp: 'とても',
    kana: 'とても',
    ro: 'totemo',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '별로',
    jp: 'あまり',
    kana: 'あまり',
    ro: 'amari',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '전혀',
    jp: '全然',
    kana: 'ぜんぜん',
    ro: 'zenzen',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이미',
    jp: 'もう',
    kana: 'もう',
    ro: 'mou',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '아직',
    jp: 'まだ',
    kana: 'まだ',
    ro: 'mada',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자주',
    jp: 'よく',
    kana: 'よく',
    ro: 'yoku',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가끔',
    jp: 'たまに',
    kana: 'たまに',
    ro: 'tamani',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '때때로',
    jp: '時々',
    kana: 'ときどき',
    ro: 'tokidoki',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '이미',
    jp: 'すでに',
    kana: 'すでに',
    ro: 'sudeni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '갑자기',
    jp: '急に',
    kana: 'きゅうに',
    ro: 'kyuu ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '천천히',
    jp: 'ゆっくり',
    kana: 'ゆっくり',
    ro: 'yukkuri',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조용히',
    jp: '静かに',
    kana: 'しずかに',
    ro: 'shizuka ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '분명히',
    jp: '明らかに',
    kana: 'あきらかに',
    ro: 'akiraka ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '확실히',
    jp: '確かに',
    kana: 'たしかに',
    ro: 'tashika ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '특히',
    jp: '特に',
    kana: 'とくに',
    ro: 'toku ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '전혀',
    jp: '全く',
    kana: 'まったく',
    ro: 'mattaku',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조금',
    jp: '少し',
    kana: 'すこし',
    ro: 'sukoshi',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '충분히',
    jp: 'たっぷり',
    kana: 'たっぷり',
    ro: 'tappuri',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '완전히',
    jp: 'すっかり',
    kana: 'すっかり',
    ro: 'sukkari',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '확실히',
    jp: 'しっかり',
    kana: 'しっかり',
    ro: 'shikkari',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '느리게',
    jp: 'ゆっくり',
    kana: 'ゆっくり',
    ro: 'yukkuri',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '즉시',
    jp: 'すぐに',
    kana: 'すぐに',
    ro: 'sugu ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '언젠가',
    jp: 'いつか',
    kana: 'いつか',
    ro: 'itsuka',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가끔',
    jp: 'たまに',
    kana: 'たまに',
    ro: 'tamani',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자주',
    jp: 'しばしば',
    kana: 'しばしば',
    ro: 'shibashiba',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '아마도',
    jp: 'おそらく',
    kana: 'おそらく',
    ro: 'osoraku',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '아마',
    jp: 'おそらく',
    kana: 'おそらく',
    ro: 'osoraku',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '확실히',
    jp: '確実に',
    kana: 'かくじつに',
    ro: 'kakujitsu ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '천천히',
    jp: 'ゆっくりと',
    kana: 'ゆっくりと',
    ro: 'yukkuri to',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '즉시',
    jp: 'すぐさま',
    kana: 'すぐさま',
    ro: 'sugu sama',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '함께',
    jp: '一緒に',
    kana: 'いっしょに',
    ro: 'issho ni',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '한 번',
    jp: '一度',
    kana: 'いちど',
    ro: 'ichido',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '두 번',
    jp: '二度',
    kana: 'にど',
    ro: 'nido',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '세 번',
    jp: '三度',
    kana: 'さんど',
    ro: 'sando',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '많은',
    jp: 'たくさんの',
    kana: 'たくさんの',
    ro: 'takusan no',
    type: 'adv',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조금씩',
    jp: '少しずつ',
    kana: 'すこしずつ',
    ro: 'sukoshi zutsu',
    type: 'adv',
    example: [],
  },
];

export const adj = [
  {
    ko: '높다',
    jp: '高い',
    kana: 'たかい',
    ro: 'takai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '高',
      stemro: 'taka',
    },
  },
  {
    ko: '낮다',
    jp: '低い',
    kana: 'ひくい',
    ro: 'hikui',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '低',
      stemro: 'hiku',
    },
  },
  {
    ko: '크다',
    jp: '大きい',
    kana: 'おおきい',
    ro: 'ookii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '大き',
      stemro: 'ooki',
    },
  },
  {
    ko: '작다',
    jp: '小さい',
    kana: 'ちいさい',
    ro: 'chiisai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '小さ',
      stemro: 'chiisa',
    },
  },
  {
    ko: '새롭다',
    jp: '新しい',
    kana: 'あたらしい',
    ro: 'atarashii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '新し',
      stemro: 'atarashi',
    },
  },
  {
    ko: '오래되다',
    jp: '古い',
    kana: 'ふるい',
    ro: 'furui',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '古',
      stemro: 'furu',
    },
  },
  {
    ko: '빠르다',
    jp: '早い',
    kana: 'はやい',
    ro: 'hayai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '早',
      stemro: 'haya',
    },
  },
  {
    ko: '느리다',
    jp: '遅い',
    kana: 'おそい',
    ro: 'osoi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '遅',
      stemro: 'oso',
    },
  },
  {
    ko: '덥다',
    jp: '暑い',
    kana: 'あつい',
    ro: 'atsui',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '暑',
      stemro: 'atsu',
    },
  },
  {
    ko: '춥다',
    jp: '寒い',
    kana: 'さむい',
    ro: 'samui',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '寒',
      stemro: 'samu',
    },
  },
  {
    ko: '불명확하다',
    jp: '不明だ',
    kana: 'ふめい',
    ro: 'fumei',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '不明',
      stemro: 'fumei',
    },
  },
  {
    ko: '적절하다',
    jp: '適切だ',
    kana: 'てきせつ',
    ro: 'tekisetsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '適切',
      stemro: 'tekisetsu',
    },
  },
  {
    ko: '부적절하다',
    jp: '不適切だ',
    kana: 'ふてきせつ',
    ro: 'futekisetsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '不適切',
      stemro: 'futekisetsu',
    },
  },
  {
    ko: '쾌활하다',
    jp: '快活だ',
    kana: 'かいかつ',
    ro: 'kaikatsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '快活',
      stemro: 'kaikatsu',
    },
  },
  {
    ko: '불안하다',
    jp: '不安だ',
    kana: 'ふあん',
    ro: 'fuan',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '不安',
      stemro: 'fuan',
    },
  },
  {
    ko: '안심하다',
    jp: '安心だ',
    kana: 'あんしん',
    ro: 'anshin',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '安心',
      stemro: 'anshin',
    },
  },
  {
    ko: '밝다',
    jp: '明るい',
    kana: 'あかるい',
    ro: 'akarui',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '明る',
      stemro: 'akaru',
    },
  },
  {
    ko: '어둡다',
    jp: '暗い',
    kana: 'くらい',
    ro: 'kurai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '暗',
      stemro: 'kura',
    },
  },
  {
    ko: '즐겁다',
    jp: '楽しい',
    kana: 'たのしい',
    ro: 'tanoshii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '楽し',
      stemro: 'tanoshi',
    },
  },
  {
    ko: '슬프다',
    jp: '悲しい',
    kana: 'かなしい',
    ro: 'kanashii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '悲し',
      stemro: 'kanashi',
    },
  },
  {
    ko: '재미있다',
    jp: '面白い',
    kana: 'おもしろい',
    ro: 'omoshiroi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '面白',
      stemro: 'omoshiro',
    },
  },
  {
    ko: '어렵다',
    jp: '難しい',
    kana: 'むずかしい',
    ro: 'muzukashii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '難し',
      stemro: 'muzukashi',
    },
  },
  {
    ko: '간단하다',
    jp: '簡単だ',
    kana: 'かんたん',
    ro: 'kantan',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '簡単',
      stemro: 'kantan',
    },
  },
  {
    ko: '조용하다',
    jp: '静かだ',
    kana: 'しずか',
    ro: 'shizuka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '静か',
      stemro: 'shizuka',
    },
  },
  {
    ko: '시끄럽다',
    jp: '賑やかだ',
    kana: 'にぎやか',
    ro: 'nigiyaka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '賑やか',
      stemro: 'nigiyaka',
    },
  },
  {
    ko: '건강하다',
    jp: '元気だ',
    kana: 'げんき',
    ro: 'genki',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '元気',
      stemro: 'genki',
    },
  },
  {
    ko: '친절하다',
    jp: '優しい',
    kana: 'やさしい',
    ro: 'yasashii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '優し',
      stemro: 'yasashi',
    },
  },
  {
    ko: '엄격하다',
    jp: '厳しい',
    kana: 'きびしい',
    ro: 'kibishii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '厳し',
      stemro: 'kibishi',
    },
  },
  {
    ko: '아름답다',
    jp: '美しい',
    kana: 'うつくしい',
    ro: 'utsukushii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '美し',
      stemro: 'utsukushi',
    },
  },
  {
    ko: '추하다',
    jp: '醜い',
    kana: 'みにくい',
    ro: 'minikui',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '醜',
      stemro: 'miniku',
    },
  },
  {
    ko: '강하다',
    jp: '強い',
    kana: 'つよい',
    ro: 'tsuyoi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '強',
      stemro: 'tsuyo',
    },
  },
  {
    ko: '약하다',
    jp: '弱い',
    kana: 'よわい',
    ro: 'yowai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '弱',
      stemro: 'yowa',
    },
  },
  {
    ko: '깊다',
    jp: '深い',
    kana: 'ふかい',
    ro: 'fukai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '深',
      stemro: 'fuka',
    },
  },
  {
    ko: '얕다',
    jp: '浅い',
    kana: 'あさい',
    ro: 'asai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '浅',
      stemro: 'asa',
    },
  },
  {
    ko: '넓다',
    jp: '広い',
    kana: 'ひろい',
    ro: 'hiroi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '広',
      stemro: 'hiro',
    },
  },
  {
    ko: '좁다',
    jp: '狭い',
    kana: 'せまい',
    ro: 'semai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '狭',
      stemro: 'sema',
    },
  },
  {
    ko: '무겁다',
    jp: '重い',
    kana: 'おもい',
    ro: 'omoi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '重',
      stemro: 'omo',
    },
  },
  {
    ko: '가볍다',
    jp: '軽い',
    kana: 'かるい',
    ro: 'karui',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '軽',
      stemro: 'karu',
    },
  },
  {
    ko: '달다',
    jp: '甘い',
    kana: 'あまい',
    ro: 'amai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '甘',
      stemro: 'ama',
    },
  },
  {
    ko: '맵다',
    jp: '辛い',
    kana: 'からい',
    ro: 'karai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '辛',
      stemro: 'kara',
    },
  },
  {
    ko: '쓰다',
    jp: '苦い',
    kana: 'にがい',
    ro: 'nigai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '苦',
      stemro: 'niga',
    },
  },
  {
    ko: '시다',
    jp: '酸っぱい',
    kana: 'すっぱい',
    ro: 'suppai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '酸っぱ',
      stemro: 'suppa',
    },
  },
  {
    ko: '차갑다',
    jp: '冷たい',
    kana: 'つめたい',
    ro: 'tsumetai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '冷た',
      stemro: 'tsumeta',
    },
  },
  {
    ko: '뜨겁다',
    jp: '熱い',
    kana: 'あつい',
    ro: 'atsui',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '熱',
      stemro: 'atsu',
    },
  },
  {
    ko: '풍부하다',
    jp: '豊かだ',
    kana: 'ゆたか',
    ro: 'yutaka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '豊か',
      stemro: 'yutaka',
    },
  },
  {
    ko: '가난하다',
    jp: '貧しい',
    kana: 'まずしい',
    ro: 'mazushii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '貧し',
      stemro: 'mazushi',
    },
  },
  {
    ko: '옳다',
    jp: '正しい',
    kana: 'ただしい',
    ro: 'tadashii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '正し',
      stemro: 'tadashi',
    },
  },
  {
    ko: '틀리다',
    jp: '間違い',
    kana: 'まちがい',
    ro: 'machigai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '間違',
      stemro: 'machiga',
    },
  },
  {
    ko: '자유롭다',
    jp: '自由だ',
    kana: 'じゆう',
    ro: 'jiyuu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '自由',
      stemro: 'jiyuu',
    },
  },
  {
    ko: '바쁘다',
    jp: '忙しい',
    kana: 'いそがしい',
    ro: 'isogashii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '忙し',
      stemro: 'isogashi',
    },
  },
  {
    ko: '한가하다',
    jp: '暇だ',
    kana: 'ひま',
    ro: 'hima',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '暇',
      stemro: 'hima',
    },
  },
  {
    ko: '강력하다',
    jp: '強力だ',
    kana: 'きょうりょく',
    ro: 'kyouryoku',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '強力',
      stemro: 'kyouryoku',
    },
  },
  {
    ko: '우수하다',
    jp: '優秀だ',
    kana: 'ゆうしゅう',
    ro: 'yuushuu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '優秀',
      stemro: 'yuushuu',
    },
  },
  {
    ko: '특별하다',
    jp: '特別だ',
    kana: 'とくべつ',
    ro: 'tokubetsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '特別',
      stemro: 'tokubetsu',
    },
  },
  {
    ko: '보통이다',
    jp: '普通だ',
    kana: 'ふつう',
    ro: 'futsuu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '普通',
      stemro: 'futsuu',
    },
  },
  {
    ko: '중요하다',
    jp: '重要だ',
    kana: 'じゅうよう',
    ro: 'juuyou',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '重要',
      stemro: 'juuyou',
    },
  },
  {
    ko: '쾌적하다',
    jp: '快適だ',
    kana: 'かいてき',
    ro: 'kaiteki',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '快適',
      stemro: 'kaiteki',
    },
  },
  {
    ko: '불쾌하다',
    jp: '不快だ',
    kana: 'ふかい',
    ro: 'fukai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '不快',
      stemro: 'fukai',
    },
  },
  {
    ko: '명확하다',
    jp: '明確だ',
    kana: 'めいかく',
    ro: 'meikaku',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '明確',
      stemro: 'meikaku',
    },
  },
  {
    ko: '날카롭다',
    jp: '鋭い',
    kana: 'するどい',
    ro: 'surudoi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '鋭',
      stemro: 'surudo',
    },
  },
  {
    ko: '무디다',
    jp: '鈍い',
    kana: 'にぶい',
    ro: 'nibui',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '鈍',
      stemro: 'nibu',
    },
  },
  {
    ko: '정직하다',
    jp: '正直だ',
    kana: 'しょうじき',
    ro: 'shoujiki',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '正直',
      stemro: 'shoujiki',
    },
  },
  {
    ko: '복잡하다',
    jp: '複雑だ',
    kana: 'ふくざつ',
    ro: 'fukuzatsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '複雑',
      stemro: 'fukuzatsu',
    },
  },
  {
    ko: '훌륭하다',
    jp: '素晴らしい',
    kana: 'すばらしい',
    ro: 'subarashii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '素晴らし',
      stemro: 'subarashi',
    },
  },
  {
    ko: '어리석다',
    jp: '愚かだ',
    kana: 'おろか',
    ro: 'oroka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '愚か',
      stemro: 'oroka',
    },
  },
  {
    ko: '성실하다',
    jp: '真面目だ',
    kana: 'まじめ',
    ro: 'majime',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '真面目',
      stemro: 'majime',
    },
  },
  {
    ko: '완고하다',
    jp: '頑固だ',
    kana: 'がんこ',
    ro: 'ganko',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '頑固',
      stemro: 'ganko',
    },
  },
  {
    ko: '화려하다',
    jp: '派手だ',
    kana: 'はで',
    ro: 'hade',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '派手',
      stemro: 'hade',
    },
  },
  {
    ko: '수수하다',
    jp: '地味だ',
    kana: 'じみ',
    ro: 'jimi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '地味',
      stemro: 'jimi',
    },
  },
  {
    ko: '비싸다',
    jp: '高価だ',
    kana: 'こうか',
    ro: 'kouka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '高価',
      stemro: 'kouka',
    },
  },
  {
    ko: '싸다',
    jp: '安価だ',
    kana: 'あんか',
    ro: 'anka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '安価',
      stemro: 'anka',
    },
  },
  {
    ko: '똑똑하다',
    jp: '賢い',
    kana: 'かしこい',
    ro: 'kashikoi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '賢',
      stemro: 'kashiko',
    },
  },
  {
    ko: '멍청하다',
    jp: '馬鹿だ',
    kana: 'ばか',
    ro: 'baka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '馬鹿',
      stemro: 'baka',
    },
  },
  {
    ko: '순진하다',
    jp: '素直だ',
    kana: 'すなお',
    ro: 'sunao',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '素直',
      stemro: 'sunao',
    },
  },
  {
    ko: '비겁하다',
    jp: '卑怯だ',
    kana: 'ひきょう',
    ro: 'hikyou',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '卑怯',
      stemro: 'hikyou',
    },
  },
  {
    ko: '친절하다',
    jp: '親切だ',
    kana: 'しんせつ',
    ro: 'shinsetsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '親切',
      stemro: 'shinsetsu',
    },
  },
  {
    ko: '냉혹하다',
    jp: '冷酷だ',
    kana: 'れいこく',
    ro: 'reikoku',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '冷酷',
      stemro: 'reikoku',
    },
  },
  {
    ko: '대담하다',
    jp: '大胆だ',
    kana: 'だいたん',
    ro: 'daitan',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '大胆',
      stemro: 'daitan',
    },
  },
  {
    ko: '겁이 많다',
    jp: '臆病だ',
    kana: 'おくびょう',
    ro: 'okubyou',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '臆病',
      stemro: 'okubyou',
    },
  },
  {
    ko: '욕심 많다',
    jp: '貪欲だ',
    kana: 'どんよく',
    ro: 'donyoku',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '貪欲',
      stemro: 'donyoku',
    },
  },
  {
    ko: '깨끗하다',
    jp: '清潔だ',
    kana: 'せいけつ',
    ro: 'seiketsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '清潔',
      stemro: 'seiketsu',
    },
  },
  {
    ko: '더럽다',
    jp: '汚い',
    kana: 'きたない',
    ro: 'kitanai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '汚',
      stemro: 'kitana',
    },
  },
  {
    ko: '억지스럽다',
    jp: '強引だ',
    kana: 'ごういん',
    ro: 'gouin',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '強引',
      stemro: 'gouin',
    },
  },
  {
    ko: '신중하다',
    jp: '注意深い',
    kana: 'ちゅういぶかい',
    ro: 'chuuibukai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '注意深',
      stemro: 'chuuibuka',
    },
  },
  {
    ko: '따뜻하다',
    jp: '温かい',
    kana: 'あたたかい',
    ro: 'atatakai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '温か',
      stemro: 'atataka',
    },
  },
  {
    ko: '춥다',
    jp: '寒冷だ',
    kana: 'かんれい',
    ro: 'kanrei',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '寒冷',
      stemro: 'kanrei',
    },
  },
  {
    ko: '아프다',
    jp: '痛い',
    kana: 'いたい',
    ro: 'itai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '痛',
      stemro: 'ita',
    },
  },
  {
    ko: '편안하다',
    jp: '心地良い',
    kana: 'ここちよい',
    ro: 'kokochiyoi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '心地良',
      stemro: 'kokochiyo',
    },
  },
  {
    ko: '불쾌하다',
    jp: '不愉快だ',
    kana: 'ふゆかい',
    ro: 'fuyukai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '不愉快',
      stemro: 'fuyukai',
    },
  },
  {
    ko: '유해하다',
    jp: '有害だ',
    kana: 'ゆうがい',
    ro: 'yuugai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '有害',
      stemro: 'yuugai',
    },
  },
  {
    ko: '무해하다',
    jp: '無害だ',
    kana: 'むがい',
    ro: 'mugai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '無害',
      stemro: 'mugai',
    },
  },
  {
    ko: '감미롭다',
    jp: '甘美だ',
    kana: 'かんび',
    ro: 'kanbi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '甘美',
      stemro: 'kanbi',
    },
  },
  {
    ko: '고통스럽다',
    jp: '苦痛だ',
    kana: 'くつう',
    ro: 'kutsuu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '苦痛',
      stemro: 'kutsuu',
    },
  },
  {
    ko: '확실하다',
    jp: '確実だ',
    kana: 'かくじつ',
    ro: 'kakujitsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '確実',
      stemro: 'kakujitsu',
    },
  },
  {
    ko: '애매하다',
    jp: '曖昧だ',
    kana: 'あいまい',
    ro: 'aimai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '曖昧',
      stemro: 'aimai',
    },
  },
  {
    ko: '멋지다',
    jp: '素敵だ',
    kana: 'すてき',
    ro: 'suteki',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '素敵',
      stemro: 'suteki',
    },
  },
  {
    ko: '기묘하다',
    jp: '奇妙だ',
    kana: 'きみょう',
    ro: 'kimyou',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '奇妙',
      stemro: 'kimyou',
    },
  },
  {
    ko: '우유부단하다',
    jp: '優柔だ不断',
    kana: 'ゆうじゅうふだん',
    ro: 'yujuufudan',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '優柔だ不',
      stemro: 'yujuufudan',
    },
  },
  {
    ko: '딱딱하다',
    jp: '堅い',
    kana: 'かたい',
    ro: 'katai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '堅',
      stemro: 'kata',
    },
  },
  {
    ko: '부드럽다',
    jp: '柔らかい',
    kana: 'やわらかい',
    ro: 'yawarakai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '柔らか',
      stemro: 'yawaraka',
    },
  },
  {
    ko: '위험하다',
    jp: '危険だ',
    kana: 'きけん',
    ro: 'kiken',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '危険',
      stemro: 'kiken',
    },
  },
  {
    ko: '안전하다',
    jp: '安全だ',
    kana: 'あんぜん',
    ro: 'anzen',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '安全',
      stemro: 'anzen',
    },
  },
  {
    ko: '매끄럽다',
    jp: '滑らかだ',
    kana: 'なめらか',
    ro: 'nameraka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '滑らか',
      stemro: 'nameraka',
    },
  },
  {
    ko: '거칠다',
    jp: '荒い',
    kana: 'あらい',
    ro: 'arai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '荒',
      stemro: 'ara',
    },
  },
  {
    ko: '온화하다',
    jp: '穏やかだ',
    kana: 'おだやか',
    ro: 'odayaka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '穏やか',
      stemro: 'odayaka',
    },
  },
  {
    ko: '그립다',
    jp: '懐かしい',
    kana: 'なつかしい',
    ro: 'natsukashii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '懐かし',
      stemro: 'natsukashi',
    },
  },
  {
    ko: '호화롭다',
    jp: '豪華だ',
    kana: 'ごうか',
    ro: 'gouka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '豪華',
      stemro: 'gouka',
    },
  },
  {
    ko: '지루하다',
    jp: '退屈だ',
    kana: 'たいくつ',
    ro: 'taikutsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '退屈',
      stemro: 'taikutsu',
    },
  },
  {
    ko: '매력적이다',
    jp: '魅力的だ',
    kana: 'みりょくてき',
    ro: 'miryokuteki',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '魅力的',
      stemro: 'miryokuteki',
    },
  },
  {
    ko: '불행하다',
    jp: '不幸だ',
    kana: 'ふこう',
    ro: 'fukou',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '不幸',
      stemro: 'fukou',
    },
  },
  {
    ko: '행복하다',
    jp: '幸せだ',
    kana: 'しあわせ',
    ro: 'shiawase',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '幸せ',
      stemro: 'shiawase',
    },
  },
  {
    ko: '쾌락적이다',
    jp: '快楽だ',
    kana: 'かいらく',
    ro: 'kairaku',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '快楽',
      stemro: 'kairaku',
    },
  },
  {
    ko: '건방지다',
    jp: '生意気だ',
    kana: 'なまいき',
    ro: 'namaiki',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '生意気',
      stemro: 'namaiki',
    },
  },
  {
    ko: '조심스럽다',
    jp: '控えめだ',
    kana: 'ひかえめ',
    ro: 'hikaeme',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '控えめ',
      stemro: 'hikaeme',
    },
  },
  {
    ko: '까다롭다',
    jp: '気難しい',
    kana: 'きむずかしい',
    ro: 'kimuzukashii',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'しい',
      endingro: 'shii',
      exception: false,
      form: 'i',
      stemjp: '気難し',
      stemro: 'kimuzuka',
    },
  },
  {
    ko: '명랑하다',
    jp: '陽気だ',
    kana: 'ようき',
    ro: 'youki',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '陽気',
      stemro: 'youki',
    },
  },
  {
    ko: '튼튼하다',
    jp: '頑丈だ',
    kana: 'がんじょう',
    ro: 'ganjou',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '頑丈',
      stemro: 'ganjou',
    },
  },
  {
    ko: '약하다',
    jp: '脆い',
    kana: 'もろい',
    ro: 'moroi',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 'i',
      stemjp: '脆',
      stemro: 'moro',
    },
  },
  {
    ko: '미묘하다',
    jp: '微妙だ',
    kana: 'びみょう',
    ro: 'bimyou',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '微妙',
      stemro: 'bimyou',
    },
  },
  {
    ko: '통쾌하다',
    jp: '痛快だ',
    kana: 'つうかい',
    ro: 'tsuukai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '痛快',
      stemro: 'tsuukai',
    },
  },
  {
    ko: '심술궂다',
    jp: '意地悪だ',
    kana: 'いじわる',
    ro: 'ijiwaru',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '意地悪',
      stemro: 'ijiwaru',
    },
  },
  {
    ko: '냉담하다',
    jp: '冷淡だ',
    kana: 'れいたん',
    ro: 'reitan',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '冷淡',
      stemro: 'reitan',
    },
  },
  {
    ko: '풍만하다',
    jp: '豊満だ',
    kana: 'ほうまん',
    ro: 'houman',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '豊満',
      stemro: 'houman',
    },
  },
  {
    ko: '마르다',
    jp: '痩せる',
    kana: 'やせる',
    ro: 'yaseru',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: true,
      form: 'na',
      stemjp: 'やせ',
      stemro: 'yase',
    },
  },
  {
    ko: '기발하다',
    jp: '奇抜だ',
    kana: 'きばつ',
    ro: 'kibatsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '奇抜',
      stemro: 'kibatsu',
    },
  },
  {
    ko: '품위 있다',
    jp: '上品だ',
    kana: 'じょうひん',
    ro: 'jouhin',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '上品',
      stemro: 'jouhin',
    },
  },
  {
    ko: '품위 없다',
    jp: '下品だ',
    kana: 'げひん',
    ro: 'gehin',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '下品',
      stemro: 'gehin',
    },
  },
  {
    ko: '호쾌하다',
    jp: '豪快だ',
    kana: 'ごうかい',
    ro: 'goukai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '豪快',
      stemro: 'goukai',
    },
  },
  {
    ko: '섬세하다',
    jp: '繊細だ',
    kana: 'せんさい',
    ro: 'sensai',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '繊細',
      stemro: 'sensai',
    },
  },
  {
    ko: '고집 세다',
    jp: '強情だ',
    kana: 'ごうじょう',
    ro: 'goujou',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '強情',
      stemro: 'goujou',
    },
  },
  {
    ko: '우울하다',
    jp: '憂鬱だ',
    kana: 'ゆううつ',
    ro: 'yuuutsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '憂鬱',
      stemro: 'yuuutsu',
    },
  },
  {
    ko: '호기심 많다',
    jp: '好奇心',
    kana: 'こうきしん',
    ro: 'koukishin',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'がある',
      endingro: 'ga aru',
      exception: false,
      form: 'na',
      stemjp: 'こうきしん',
      stemro: 'koukishin',
    },
  },
  {
    ko: '게으르다',
    jp: '怠惰だ',
    kana: 'たいだ',
    ro: 'taida',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '怠惰',
      stemro: 'taida',
    },
  },
  {
    ko: '근면하다',
    jp: '勤勉だ',
    kana: 'きんべん',
    ro: 'kinben',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '勤勉',
      stemro: 'kinben',
    },
  },
  {
    ko: '대담무쌍하다',
    jp: '大胆不敵',
    kana: 'だいたんふてき',
    ro: 'daitanfuteki',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'な',
      endingro: 'na',
      exception: false,
      form: 'na',
      stemjp: 'だいたんふてき',
      stemro: 'daitanfuteki',
    },
  },
  {
    ko: '열심히 하다',
    jp: '一生懸命',
    kana: 'いっしょうけんめい',
    ro: 'isshoukenmei',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'に',
      endingro: 'ni',
      exception: false,
      form: 'na',
      stemjp: 'いっしょうけんめい',
      stemro: 'isshoukenmei',
    },
  },
  {
    ko: '편협하다',
    jp: '偏屈だ',
    kana: 'へんくつ',
    ro: 'henkutsu',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'だ',
      endingro: 'da',
      exception: false,
      form: 'na',
      stemjp: '偏屈',
      stemro: 'henkutsu',
    },
  },
  {
    ko: '강경하다',
    jp: '強気',
    kana: 'つよき',
    ro: 'tsuyoki',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'な',
      endingro: 'na',
      exception: false,
      form: 'na',
      stemjp: 'つよき',
      stemro: 'tsuyoki',
    },
  },
  {
    ko: '냉정하다',
    jp: '冷静',
    kana: 'れいせい',
    ro: 'reisei',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'な',
      endingro: 'na',
      exception: false,
      form: 'na',
      stemjp: 'れいせい',
      stemro: 'reisei',
    },
  },
  {
    ko: '격렬하다',
    jp: '激情',
    kana: 'げきじょう',
    ro: 'gekijou',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: '的な',
      endingro: 'tekina',
      exception: false,
      form: 'na',
      stemjp: 'げきじょう',
      stemro: 'gekijou',
    },
  },
  {
    ko: '건강하다',
    jp: '健やか',
    kana: 'すこやか',
    ro: 'sukoyaka',
    type: 'adj',
    language: 'japanese',
    etc: {
      endingjp: 'な',
      endingro: 'na',
      exception: false,
      form: 'na',
      stemjp: 'すこやか',
      stemro: 'sukoyaka',
    },
  },
];

export const noun: Word<Noun>[] = [
  {
    language: 'japanese',
    ko: '학교',
    jp: '学校',
    kana: 'がっこう',
    ro: 'gakkou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '선생님',
    jp: '先生',
    kana: 'せんせい',
    ro: 'sensei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '학생',
    jp: '学生',
    kana: 'がくせい',
    ro: 'gakusei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '책',
    jp: '本',
    kana: 'ほん',
    ro: 'hon',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자동차',
    jp: '車',
    kana: 'くるま',
    ro: 'kuruma',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '집',
    jp: '家',
    kana: 'いえ',
    ro: 'ie',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '개',
    jp: '犬',
    kana: 'いぬ',
    ro: 'inu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '고양이',
    jp: '猫',
    kana: 'ねこ',
    ro: 'neko',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '음식',
    jp: '食べ物',
    kana: 'たべもの',
    ro: 'tabemono',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '음료',
    jp: '飲み物',
    kana: 'のみもの',
    ro: 'nomimono',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '친구',
    jp: '友達',
    kana: 'ともだち',
    ro: 'tomodachi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가족',
    jp: '家族',
    kana: 'かぞく',
    ro: 'kazoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '일',
    jp: '仕事',
    kana: 'しごと',
    ro: 'shigoto',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '시간',
    jp: '時間',
    kana: 'じかん',
    ro: 'jikan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '돈',
    jp: 'お金',
    kana: 'おかね',
    ro: 'okane',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '날씨',
    jp: '天気',
    kana: 'てんき',
    ro: 'tenki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기분',
    jp: '気持ち',
    kana: 'きもち',
    ro: 'kimochi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '장소',
    jp: '場所',
    kana: 'ばしょ',
    ro: 'basho',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '길',
    jp: '道',
    kana: 'みち',
    ro: 'michi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '산',
    jp: '山',
    kana: 'やま',
    ro: 'yama',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '강',
    jp: '川',
    kana: 'かわ',
    ro: 'kawa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '바다',
    jp: '海',
    kana: 'うみ',
    ro: 'umi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '하늘',
    jp: '空',
    kana: 'そら',
    ro: 'sora',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '별',
    jp: '星',
    kana: 'ほし',
    ro: 'hoshi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '달',
    jp: '月',
    kana: 'つき',
    ro: 'tsuki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '꽃',
    jp: '花',
    kana: 'はな',
    ro: 'hana',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '나무',
    jp: '木',
    kana: 'き',
    ro: 'ki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '풀',
    jp: '草',
    kana: 'くさ',
    ro: 'kusa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '흙',
    jp: '土',
    kana: 'つち',
    ro: 'tsuchi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '불',
    jp: '火',
    kana: 'ひ',
    ro: 'hi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '물',
    jp: '水',
    kana: 'みず',
    ro: 'mizu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '바람',
    jp: '風',
    kana: 'かぜ',
    ro: 'kaze',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '소리',
    jp: '音',
    kana: 'おと',
    ro: 'oto',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '목소리',
    jp: '声',
    kana: 'こえ',
    ro: 'koe',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '빛',
    jp: '光',
    kana: 'ひかり',
    ro: 'hikari',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '그림자',
    jp: '影',
    kana: 'かげ',
    ro: 'kage',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '꿈',
    jp: '夢',
    kana: 'ゆめ',
    ro: 'yume',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '마음',
    jp: '心',
    kana: 'こころ',
    ro: 'kokoro',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '추억',
    jp: '思い出',
    kana: 'おもいで',
    ro: 'omoide',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '감정',
    jp: '感情',
    kana: 'かんじょう',
    ro: 'kanjou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '사랑',
    jp: '愛',
    kana: 'あい',
    ro: 'ai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '희망',
    jp: '希望',
    kana: 'きぼう',
    ro: 'kibou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '두려움',
    jp: '恐れ',
    kana: 'おそれ',
    ro: 'osore',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '슬픔',
    jp: '悲しみ',
    kana: 'かなしみ',
    ro: 'kanashimi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기쁨',
    jp: '喜び',
    kana: 'よろこび',
    ro: 'yorokobi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '분노',
    jp: '怒り',
    kana: 'いかり',
    ro: 'ikari',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '행복',
    jp: '幸せ',
    kana: 'しあわせ',
    ro: 'shiawase',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '건강',
    jp: '健康',
    kana: 'けんこう',
    ro: 'kenkou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '병',
    jp: '病気',
    kana: 'びょうき',
    ro: 'byouki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '치료',
    jp: '治療',
    kana: 'ちりょう',
    ro: 'chiryou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '운동',
    jp: '運動',
    kana: 'うんどう',
    ro: 'undou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '식사',
    jp: '食事',
    kana: 'しょくじ',
    ro: 'shokuji',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '휴식',
    jp: '休み',
    kana: 'やすみ',
    ro: 'yasumi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '여행',
    jp: '旅行',
    kana: 'りょこう',
    ro: 'ryokou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '문화',
    jp: '文化',
    kana: 'ぶんか',
    ro: 'bunka',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '역사',
    jp: '歴史',
    kana: 'れきし',
    ro: 'rekishi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '언어',
    jp: '言語',
    kana: 'げんご',
    ro: 'gengo',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '문학',
    jp: '文学',
    kana: 'ぶんがく',
    ro: 'bungaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '음악',
    jp: '音楽',
    kana: 'おんがく',
    ro: 'ongaku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '미술',
    jp: '美術',
    kana: 'びじゅつ',
    ro: 'bijutsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '영화',
    jp: '映画',
    kana: 'えいが',
    ro: 'eiga',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '스포츠',
    jp: 'スポーツ',
    kana: 'すぽーつ',
    ro: 'supōtsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '게임',
    jp: 'ゲーム',
    kana: 'げーむ',
    ro: 'gēmu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '취미',
    jp: '趣味',
    kana: 'しゅみ',
    ro: 'shumi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '직업',
    jp: '仕事',
    kana: 'しごと',
    ro: 'shigoto',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '회사',
    jp: '会社',
    kana: 'かいしゃ',
    ro: 'kaisha',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '학교',
    jp: '学校',
    kana: 'がっこう',
    ro: 'gakkou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '교실',
    jp: '教室',
    kana: 'きょうしつ',
    ro: 'kyoushitsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '도서관',
    jp: '図書館',
    kana: 'としょかん',
    ro: 'toshokan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '공원',
    jp: '公園',
    kana: 'こうえん',
    ro: 'kouen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '미술관',
    jp: '美術館',
    kana: 'びじゅつかん',
    ro: 'bijutsukan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '박물관',
    jp: '博物館',
    kana: 'はくぶつかん',
    ro: 'hakubutsukan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '시장',
    jp: '市場',
    kana: 'いちば',
    ro: 'ichiba',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가게',
    jp: '店',
    kana: 'みせ',
    ro: 'mise',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '레스토랑',
    jp: 'レストラン',
    kana: 'れすとらん',
    ro: 'resutoran',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '카페',
    jp: 'カフェ',
    kana: 'かふぇ',
    ro: 'kafe',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '바',
    jp: 'バー',
    kana: 'ばー',
    ro: 'baa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '호텔',
    jp: 'ホテル',
    kana: 'ほてる',
    ro: 'hoteru',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '여관',
    jp: '旅館',
    kana: 'りょかん',
    ro: 'ryokan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '온천',
    jp: '温泉',
    kana: 'おんせん',
    ro: 'onsen',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '해수욕',
    jp: '海水浴',
    kana: 'かいすいよく',
    ro: 'kaisuiyoku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '등산',
    jp: '山登り',
    kana: 'やまのぼり',
    ro: 'yamanobori',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '캠프',
    jp: 'キャンプ',
    kana: 'きゃんぷ',
    ro: 'kyanpu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '하이킹',
    jp: 'ハイキング',
    kana: 'はいきんぐ',
    ro: 'haikingu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '소풍',
    jp: 'ピクニック',
    kana: 'ぴくにっく',
    ro: 'pikunikku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '스포츠카',
    jp: 'スポーツカー',
    kana: 'すぽーつかー',
    ro: 'supōtsukā',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '버스',
    jp: 'バス',
    kana: 'ばす',
    ro: 'basu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '전철',
    jp: '電車',
    kana: 'でんしゃ',
    ro: 'densha',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '비행기',
    jp: '飛行機',
    kana: 'ひこうき',
    ro: 'hikouki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '배',
    jp: '船',
    kana: 'ふね',
    ro: 'fune',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '자전거',
    jp: '自転車',
    kana: 'じてんしゃ',
    ro: 'jitensha',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '오토바이',
    jp: 'バイク',
    kana: 'ばいく',
    ro: 'baiku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '도구',
    jp: '道具',
    kana: 'どうぐ',
    ro: 'dougu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '기계',
    jp: '機械',
    kana: 'きかい',
    ro: 'kikai',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가구',
    jp: '家具',
    kana: 'かぐ',
    ro: 'kagu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '전기',
    jp: '電気',
    kana: 'でんき',
    ro: 'denki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '수도',
    jp: '水道',
    kana: 'すいどう',
    ro: 'suidou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가스',
    jp: 'ガス',
    kana: 'がす',
    ro: 'gasu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '전화',
    jp: '電話',
    kana: 'でんわ',
    ro: 'denwa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '인터넷',
    jp: 'インターネット',
    kana: 'いんたーねっと',
    ro: 'intānetto',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '텔레비전',
    jp: 'テレビ',
    kana: 'てれび',
    ro: 'terebi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '라디오',
    jp: 'ラジオ',
    kana: 'らじお',
    ro: 'rajio',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '카메라',
    jp: 'カメラ',
    kana: 'かめら',
    ro: 'kamera',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '컴퓨터',
    jp: 'コンピュータ',
    kana: 'こんぴゅーた',
    ro: 'konpyūta',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '스마트폰',
    jp: 'スマートフォン',
    kana: 'すまーとふぉん',
    ro: 'sumātofon',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '태블릿',
    jp: 'タブレット',
    kana: 'たぶれっと',
    ro: 'taburetto',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '게임기',
    jp: 'ゲーム機',
    kana: 'げーむき',
    ro: 'gēmuki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '책장',
    jp: '本棚',
    kana: 'ほんだな',
    ro: 'hondana',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '책상',
    jp: '机',
    kana: 'つくえ',
    ro: 'tsukue',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '의자',
    jp: '椅子',
    kana: 'いす',
    ro: 'isu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '침대',
    jp: 'ベッド',
    kana: 'べっど',
    ro: 'beddo',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '소파',
    jp: 'ソファ',
    kana: 'そふぁ',
    ro: 'sofa',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '커튼',
    jp: 'カーテン',
    kana: 'かーてん',
    ro: 'kāten',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '카펫',
    jp: '絨毯',
    kana: 'じゅうたん',
    ro: 'juutan',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '조명',
    jp: '照明',
    kana: 'しょうめい',
    ro: 'shoumei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '시계',
    jp: '時計',
    kana: 'とけい',
    ro: 'tokei',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '거울',
    jp: '鏡',
    kana: 'かがみ',
    ro: 'kagami',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '사진',
    jp: '写真',
    kana: 'しゃしん',
    ro: 'shashin',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '그림',
    jp: '絵',
    kana: 'え',
    ro: 'e',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '포스터',
    jp: 'ポスター',
    kana: 'ぽすたー',
    ro: 'posutā',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '책',
    jp: '本',
    kana: 'ほん',
    ro: 'hon',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '잡지',
    jp: '雑誌',
    kana: 'ざっし',
    ro: 'zasshi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '신문',
    jp: '新聞',
    kana: 'しんぶん',
    ro: 'shinbun',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '편지',
    jp: '手紙',
    kana: 'てがみ',
    ro: 'tegami',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '봉투',
    jp: '封筒',
    kana: 'ふうとう',
    ro: 'fuutou',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '우표',
    jp: '切手',
    kana: 'きって',
    ro: 'kitte',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '명함',
    jp: '名刺',
    kana: 'めいし',
    ro: 'meishi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '달력',
    jp: 'カレンダー',
    kana: 'かれんだー',
    ro: 'karendā',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '일기',
    jp: '日記',
    kana: 'にっき',
    ro: 'nikki',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '사전',
    jp: '辞書',
    kana: 'じしょ',
    ro: 'jisho',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '지도',
    jp: '地図',
    kana: 'ちず',
    ro: 'chizu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '안내서',
    jp: 'ガイドブック',
    kana: 'がいどぶっく',
    ro: 'gaidobukku',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '여행 가이드',
    jp: '旅行ガイド',
    kana: 'りょこうがいど',
    ro: 'ryokougaido',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '티켓',
    jp: 'チケット',
    kana: 'ちけっと',
    ro: 'chiketto',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '여권',
    jp: 'パスポート',
    kana: 'ぱすぽーと',
    ro: 'pasupōto',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '지갑',
    jp: '財布',
    kana: 'さいふ',
    ro: 'saifu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '열쇠',
    jp: '鍵',
    kana: 'かぎ',
    ro: 'kagi',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '가방',
    jp: 'バッグ',
    kana: 'ばっぐ',
    ro: 'baggu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '신발',
    jp: '靴',
    kana: 'くつ',
    ro: 'kutsu',
    type: 'noun',
    example: [],
  },
  {
    language: 'japanese',
    ko: '옷',
    jp: '服',
    kana: 'ふく',
    ro: 'fuku',
    type: 'noun',
    example: [],
  },
];

export const good: Word<Verb>[] = [
  {
    id: '',
    ko: '가다',
    jp: '行く',
    kana: 'いく',
    ro: 'iku',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: true,
      form: 1,
      stemjp: '行',
      stemro: 'i',
    },
  },
  {
    id: '',
    ko: '쓰다',
    jp: '書く',
    kana: 'かく',
    ro: 'kaku',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '書',
      stemro: 'ka',
    },
  },
  {
    id: '',
    ko: '먹다',
    jp: '食べる',
    kana: 'たべる',
    ro: 'taberu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '食べ',
      stemro: 'tabe',
    },
  },
  {
    id: '',
    ko: '마시다',
    jp: '飲む',
    kana: 'のむ',
    ro: 'nomu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '飲',
      stemro: 'no',
    },
  },
  {
    id: '',
    ko: '보다',
    jp: '見る',
    kana: 'みる',
    ro: 'miru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '見',
      stemro: 'mi',
    },
  },
  {
    id: '',
    ko: '듣다',
    jp: '聞く',
    kana: 'きく',
    ro: 'kiku',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '聞',
      stemro: 'ki',
    },
  },
  {
    id: '',
    ko: '이야기하다',
    jp: '話す',
    kana: 'はなす',
    ro: 'hanasu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '話',
      stemro: 'hana',
    },
  },
  {
    id: '',
    ko: '사다',
    jp: '買う',
    kana: 'かう',
    ro: 'kau',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '買',
      stemro: 'ka',
    },
  },
  {
    id: '',
    ko: '팔다',
    jp: '売る',
    kana: 'うる',
    ro: 'uru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '売',
      stemro: 'u',
    },
  },
  {
    id: '',
    ko: '자다',
    jp: '寝る',
    kana: 'ねる',
    ro: 'neru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '寝',
      stemro: 'ne',
    },
  },
  {
    id: '',
    ko: '일어나다',
    jp: '起きる',
    kana: 'おきる',
    ro: 'okiru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '起き',
      stemro: 'oki',
    },
  },
  {
    id: '',
    ko: '놀다',
    jp: '遊ぶ',
    kana: 'あそぶ',
    ro: 'asobu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'ぶ',
      endingro: 'bu',
      exception: false,
      form: 1,
      stemjp: '遊',
      stemro: 'aso',
    },
  },
  {
    id: '',
    ko: '일하다',
    jp: '働く',
    kana: 'はたらく',
    ro: 'hataraku',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '働',
      stemro: 'hatara',
    },
  },
  {
    id: '',
    ko: '가르치다',
    jp: '教える',
    kana: 'おしえる',
    ro: 'oshieru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '教え',
      stemro: 'oshie',
    },
  },
  {
    id: '',
    ko: '배우다',
    jp: '習う',
    kana: 'ならう',
    ro: 'narau',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '習',
      stemro: 'nara',
    },
  },
  {
    id: '',
    ko: '시작하다',
    jp: '始める',
    kana: 'はじめる',
    ro: 'hajimeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '始め',
      stemro: 'hajime',
    },
  },
  {
    id: '',
    ko: '끝나다',
    jp: '終わる',
    kana: 'おわる',
    ro: 'owaru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '終わ',
      stemro: 'owa',
    },
  },
  {
    id: '',
    ko: '배우다',
    jp: '教わる',
    kana: 'おそわる',
    ro: 'osowaru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '教わ',
      stemro: 'osowa',
    },
  },
  {
    id: '',
    ko: '조사하다',
    jp: '調べる',
    kana: 'しらべる',
    ro: 'shiraberu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '調べ',
      stemro: 'shirabe',
    },
  },
  {
    id: '',
    ko: '맡기다',
    jp: '預ける',
    kana: 'あずける',
    ro: 'azukeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '預け',
      stemro: 'azuke',
    },
  },
  {
    id: '',
    ko: '따뜻하게하다',
    jp: '暖める',
    kana: 'あたためる',
    ro: 'atatameru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '暖め',
      stemro: 'atatame',
    },
  },
  {
    id: '',
    ko: '다루다',
    jp: '扱う',
    kana: 'あつかう',
    ro: 'atsukau',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '扱',
      stemro: 'atsuka',
    },
  },
  {
    id: '',
    ko: '변하다',
    jp: '変わる',
    kana: 'かわる',
    ro: 'kawaru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '変わ',
      stemro: 'kawa',
    },
  },
  {
    id: '',
    ko: '지우다',
    jp: '消す',
    kana: 'けす',
    ro: 'kesu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '消',
      stemro: 'ke',
    },
  },
  {
    id: '',
    ko: '기르다',
    jp: '育てる',
    kana: 'そだてる',
    ro: 'sodateru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '育て',
      stemro: 'sodate',
    },
  },
  {
    id: '',
    ko: '지키다',
    jp: '守る',
    kana: 'まもる',
    ro: 'mamoru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '守',
      stemro: 'mamo',
    },
  },
  {
    id: '',
    ko: '나아가다',
    jp: '進む',
    kana: 'すすむ',
    ro: 'susumu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '進',
      stemro: 'susu',
    },
  },
  {
    id: '',
    ko: '돌아가다',
    jp: '戻る',
    kana: 'もどる',
    ro: 'modoru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '戻',
      stemro: 'modo',
    },
  },
  {
    id: '',
    ko: '줄다',
    jp: '減る',
    kana: 'へる',
    ro: 'heru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '減',
      stemro: 'he',
    },
  },
  {
    id: '',
    ko: '늘다',
    jp: '増える',
    kana: 'ふえる',
    ro: 'fueru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '増え',
      stemro: 'fue',
    },
  },
  {
    id: '',
    ko: '계속되다',
    jp: '続く',
    kana: 'つづく',
    ro: 'tsuzuku',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '続',
      stemro: 'tsuzu',
    },
  },
  {
    id: '',
    ko: '결정되다',
    jp: '決まる',
    kana: 'きまる',
    ro: 'kimaru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '決ま',
      stemro: 'kima',
    },
  },
  {
    id: '',
    ko: '결정하다',
    jp: '決める',
    kana: 'きめる',
    ro: 'kimeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '決め',
      stemro: 'kime',
    },
  },
  {
    id: '',
    ko: '받다',
    jp: '受ける',
    kana: 'うける',
    ro: 'ukeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '受け',
      stemro: 'uke',
    },
  },
  {
    id: '',
    ko: '주다',
    jp: '与える',
    kana: 'あたえる',
    ro: 'ataeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '与え',
      stemro: 'atae',
    },
  },
  {
    id: '',
    ko: '선택하다',
    jp: '選択する',
    kana: 'せんたくする',
    ro: 'sentakusuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '選択',
      stemro: 'sentaku',
    },
  },
  {
    id: '',
    ko: '발견하다',
    jp: '発見する',
    kana: 'はっけんする',
    ro: 'hakkensuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '発見',
      stemro: 'hakken',
    },
  },
  {
    id: '',
    ko: '해결하다',
    jp: '解決する',
    kana: 'かいけつする',
    ro: 'kaiketsusuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '解決',
      stemro: 'kaiketsu',
    },
  },
  {
    id: '',
    ko: '이용하다',
    jp: '利用する',
    kana: 'りようする',
    ro: 'riyousuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '利用',
      stemro: 'riyou',
    },
  },
  {
    id: '',
    ko: '조사하다',
    jp: '調査する',
    kana: 'ちょうさする',
    ro: 'chousasuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '調査',
      stemro: 'chousa',
    },
  },
  {
    id: '',
    ko: '기록하다',
    jp: '記録する',
    kana: 'きろくする',
    ro: 'kirokusuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '記録',
      stemro: 'kiroku',
    },
  },
  {
    id: '',
    ko: '선택하다',
    jp: '選ぶ',
    kana: 'えらぶ',
    ro: 'erabu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'ぶ',
      endingro: 'bu',
      exception: false,
      form: 1,
      stemjp: '選',
      stemro: 'era',
    },
  },
  {
    id: '',
    ko: '운반하다',
    jp: '運ぶ',
    kana: 'はこぶ',
    ro: 'hakobu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'ぶ',
      endingro: 'bu',
      exception: false,
      form: 1,
      stemjp: '運',
      stemro: 'hako',
    },
  },
  {
    id: '',
    ko: '시험하다',
    jp: '試す',
    kana: 'ためす',
    ro: 'tamesu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '試',
      stemro: 'tame',
    },
  },
  {
    id: '',
    ko: '웃다',
    jp: '笑う',
    kana: 'わらう',
    ro: 'warau',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '笑',
      stemro: 'wara',
    },
  },
  {
    id: '',
    ko: '기다리다',
    jp: '待つ',
    kana: 'まつ',
    ro: 'matsu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'つ',
      endingro: 'tsu',
      exception: false,
      form: 1,
      stemjp: '待',
      stemro: 'ma',
    },
  },
  {
    id: '',
    ko: '사용하다',
    jp: '使う',
    kana: 'つかう',
    ro: 'tsukau',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '使',
      stemro: 'tsuka',
    },
  },
  {
    id: '',
    ko: '만들다',
    jp: '作る',
    kana: 'つくる',
    ro: 'tsukuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '作',
      stemro: 'tsuku',
    },
  },
  {
    id: '',
    ko: '알다',
    jp: '知る',
    kana: 'しる',
    ro: 'shiru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '知',
      stemro: 'shi',
    },
  },
  {
    id: '',
    ko: '생각하다',
    jp: '思う',
    kana: 'おもう',
    ro: 'omou',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '思',
      stemro: 'omo',
    },
  },
  {
    id: '',
    ko: '느끼다',
    jp: '感じる',
    kana: 'かんじる',
    ro: 'kanjiru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '感じ',
      stemro: 'kanji',
    },
  },
  {
    id: '',
    ko: '생각하다',
    jp: '考える',
    kana: 'かんがえる',
    ro: 'kangaeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '考え',
      stemro: 'kangae',
    },
  },
  {
    id: '',
    ko: '믿다',
    jp: '信じる',
    kana: 'しんじる',
    ro: 'shinjiru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '信じ',
      stemro: 'shinji',
    },
  },
  {
    id: '',
    ko: '잊다',
    jp: '忘れる',
    kana: 'わすれる',
    ro: 'wasureru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '忘れ',
      stemro: 'wasure',
    },
  },
  {
    id: '',
    ko: '기억해내다',
    jp: '思い出す',
    kana: 'おもいだす',
    ro: 'omoidasu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'す',
      endingro: 'su',
      exception: false,
      form: 1,
      stemjp: '思い出',
      stemro: 'omoida',
    },
  },
  {
    id: '',
    ko: '돕다',
    jp: '助ける',
    kana: 'たすける',
    ro: 'tasukeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '助け',
      stemro: 'tasuke',
    },
  },
  {
    id: '',
    ko: '바꾸다',
    jp: '変える',
    kana: 'かえる',
    ro: 'kaeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '変え',
      stemro: 'kae',
    },
  },
  {
    id: '',
    ko: '계속하다',
    jp: '続ける',
    kana: 'つづける',
    ro: 'tsuzukeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '続け',
      stemro: 'tsuzuke',
    },
  },
  {
    id: '',
    ko: '그만두다',
    jp: '止める',
    kana: 'やめる',
    ro: 'yameru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '止め',
      stemro: 'yame',
    },
  },
  {
    id: '',
    ko: '들어가다',
    jp: '入る',
    kana: 'はいる',
    ro: 'hairu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: true,
      form: 1,
      stemjp: '入',
      stemro: 'hai',
    },
  },
  {
    id: '',
    ko: '나가다',
    jp: '出る',
    kana: 'でる',
    ro: 'deru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '出',
      stemro: 'de',
    },
  },
  {
    id: '',
    ko: '타다',
    jp: '乗る',
    kana: 'のる',
    ro: 'noru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '乗',
      stemro: 'no',
    },
  },
  {
    id: '',
    ko: '내리다',
    jp: '降りる',
    kana: 'おりる',
    ro: 'oriru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '降り',
      stemro: 'ori',
    },
  },
  {
    id: '',
    ko: '수영하다',
    jp: '泳ぐ',
    kana: 'およぐ',
    ro: 'oyogu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'ぐ',
      endingro: 'gu',
      exception: false,
      form: 1,
      stemjp: '泳',
      stemro: 'oyo',
    },
  },
  {
    id: '',
    ko: '달리다',
    jp: '走る',
    kana: 'はしる',
    ro: 'hashiru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: true,
      form: 1,
      stemjp: '走',
      stemro: 'hashi',
    },
  },
  {
    id: '',
    ko: '날다',
    jp: '飛ぶ',
    kana: 'とぶ',
    ro: 'tobu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'ぶ',
      endingro: 'bu',
      exception: false,
      form: 1,
      stemjp: '飛',
      stemro: 'to',
    },
  },
  {
    id: '',
    ko: '웃음',
    jp: '笑い',
    kana: 'わらい',
    ro: 'warai',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'い',
      endingro: 'i',
      exception: false,
      form: 1,
      stemjp: '笑',
      stemro: 'wara',
    },
  },
  {
    id: '',
    ko: '울다',
    jp: '泣く',
    kana: 'なく',
    ro: 'naku',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '泣',
      stemro: 'na',
    },
  },
  {
    id: '',
    ko: '외치다',
    jp: '叫ぶ',
    kana: 'さけぶ',
    ro: 'sakebu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'ぶ',
      endingro: 'bu',
      exception: false,
      form: 1,
      stemjp: '叫',
      stemro: 'sake',
    },
  },
  {
    id: '',
    ko: '그리다',
    jp: '描く',
    kana: 'えがく',
    ro: 'egaku',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '描',
      stemro: 'ega',
    },
  },
  {
    id: '',
    ko: '닦다',
    jp: '磨く',
    kana: 'みがく',
    ro: 'migaku',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'く',
      endingro: 'ku',
      exception: false,
      form: 1,
      stemjp: '磨',
      stemro: 'miga',
    },
  },
  {
    id: '',
    ko: '청소하다',
    jp: '掃除する',
    kana: 'そうじする',
    ro: 'soujisuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '掃除',
      stemro: 'souji',
    },
  },
  {
    id: '',
    ko: '운전하다',
    jp: '運転する',
    kana: 'うんてんする',
    ro: 'untensuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '運転',
      stemro: 'unten',
    },
  },
  {
    id: '',
    ko: '공부하다',
    jp: '勉強する',
    kana: 'べんきょうする',
    ro: 'benkyousuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '勉強',
      stemro: 'benkyou',
    },
  },
  {
    id: '',
    ko: '여행하다',
    jp: '旅行する',
    kana: 'りょこうする',
    ro: 'ryokousuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '旅行',
      stemro: 'ryokou',
    },
  },
  {
    id: '',
    ko: '약속하다',
    jp: '約束する',
    kana: 'やくそくする',
    ro: 'yakusokusuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '約束',
      stemro: 'yakusoku',
    },
  },
  {
    id: '',
    ko: '설명하다',
    jp: '説明する',
    kana: 'せつめいする',
    ro: 'setsumeisuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '説明',
      stemro: 'setsumei',
    },
  },
  {
    id: '',
    ko: '참가하다',
    jp: '参加する',
    kana: 'さんかする',
    ro: 'sankasuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '参加',
      stemro: 'sanka',
    },
  },
  {
    id: '',
    ko: '발표하다',
    jp: '発表する',
    kana: 'はっぴょうする',
    ro: 'happyousuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '発表',
      stemro: 'happyou',
    },
  },
  {
    id: '',
    ko: '운영하다',
    jp: '運営する',
    kana: 'うんえいする',
    ro: "un'eisuru",
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '運営',
      stemro: "un'ei",
    },
  },
  {
    id: '',
    ko: '조정하다',
    jp: '調整する',
    kana: 'ちょうせいする',
    ro: 'chouseisuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '調整',
      stemro: 'chousei',
    },
  },
  {
    id: '',
    ko: '개선하다',
    jp: '改善する',
    kana: 'かいぜんする',
    ro: 'kaizensuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '改善',
      stemro: 'kaizen',
    },
  },
  {
    id: '',
    ko: '확인하다',
    jp: '確認する',
    kana: 'かくにんする',
    ro: 'kakuninsuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '確認',
      stemro: 'kakunin',
    },
  },
  {
    id: '',
    ko: '보고하다',
    jp: '報告する',
    kana: 'ほうこくする',
    ro: 'houkokusuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '報告',
      stemro: 'houkoku',
    },
  },
  {
    id: '',
    ko: '계획하다',
    jp: '計画する',
    kana: 'けいかくする',
    ro: 'keikakusuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '計画',
      stemro: 'keikaku',
    },
  },
  {
    id: '',
    ko: '준비하다',
    jp: '準備する',
    kana: 'じゅんびする',
    ro: 'junbisuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '準備',
      stemro: 'junbi',
    },
  },
  {
    id: '',
    ko: '저장하다',
    jp: '保存する',
    kana: 'ほぞんする',
    ro: 'hozonsuru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'する',
      endingro: 'suru',
      exception: false,
      form: 3,
      stemjp: '保存',
      stemro: 'hozon',
    },
  },
  {
    id: '',
    ko: '씻다',
    jp: '洗う',
    kana: 'あらう',
    ro: 'arau',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'う',
      endingro: 'u',
      exception: false,
      form: 1,
      stemjp: '洗',
      stemro: 'ara',
    },
  },
  {
    id: '',
    ko: '자르다',
    jp: '切る',
    kana: 'きる',
    ro: 'kiru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: true,
      form: 1,
      stemjp: '切',
      stemro: 'ki',
    },
  },
  {
    id: '',
    ko: '닫다',
    jp: '閉める',
    kana: 'しめる',
    ro: 'shimeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '閉め',
      stemro: 'shime',
    },
  },
  {
    id: '',
    ko: '열다',
    jp: '開ける',
    kana: 'あける',
    ro: 'akeru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 2,
      stemjp: '開け',
      stemro: 'ake',
    },
  },
  {
    id: '',
    ko: '입다',
    jp: '着る',
    kana: 'きる',
    ro: 'kiru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: true,
      form: 2,
      stemjp: '着',
      stemro: 'ki',
    },
  },
  {
    id: '',
    ko: '벗다',
    jp: '脱ぐ',
    kana: 'ぬぐ',
    ro: 'nugu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'ぐ',
      endingro: 'gu',
      exception: false,
      form: 1,
      stemjp: '脱',
      stemro: 'nu',
    },
  },
  {
    id: '',
    ko: '뛰어들다',
    jp: '飛び込む',
    kana: 'とびこむ',
    ro: 'tobikomu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'む',
      endingro: 'mu',
      exception: false,
      form: 1,
      stemjp: '飛び込',
      stemro: 'tobiko',
    },
  },
  {
    id: '',
    ko: '오르다',
    jp: '登る',
    kana: 'のぼる',
    ro: 'noboru',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: false,
      form: 1,
      stemjp: '登',
      stemro: 'nobo',
    },
  },
  {
    id: '',
    ko: '비내리다',
    jp: '降る',
    kana: 'ふる',
    ro: 'furu',
    type: 'verb',
    language: 'japanese',
    etc: {
      endingjp: 'る',
      endingro: 'ru',
      exception: true,
      form: 1,
      stemjp: '降',
      stemro: 'fu',
    },
  },
];

export const hiragana = {
  a: [
    { jp: 'あ', ro: 'a', ko: '아' },
    { jp: 'い', ro: 'i', ko: '이' },
    { jp: 'う', ro: 'u', ko: '우' },
    { jp: 'え', ro: 'e', ko: '에' },
    { jp: 'お', ro: 'o', ko: '오' },
  ],
  ka: [
    { jp: 'か', ro: 'ka', ko: '카' },
    { jp: 'き', ro: 'ki', ko: '키' },
    { jp: 'く', ro: 'ku', ko: '쿠' },
    { jp: 'け', ro: 'ke', ko: '케' },
    { jp: 'こ', ro: 'ko', ko: '코' },
  ],
  sa: [
    { jp: 'さ', ro: 'sa', ko: '사' },
    { jp: 'し', ro: 'shi', ko: '시' },
    { jp: 'す', ro: 'su', ko: '스' },
    { jp: 'せ', ro: 'se', ko: '세' },
    { jp: 'そ', ro: 'so', ko: '소' },
    { jp: 'しゃ', ro: 'sha', ko: '샤' },
    { jp: 'しゅ', ro: 'shu', ko: '슈' },
    { jp: 'しょ', ro: 'sho', ko: '쇼' },
  ],
  ta: [
    { jp: 'た', ro: 'ta', ko: '타' },
    { jp: 'ち', ro: 'chi', ko: '치' },
    { jp: 'つ', ro: 'tsu', ko: '츠' },
    { jp: 'っ', ro: 't', ko: '츠' },
    { jp: 'て', ro: 'te', ko: '테' },
    { jp: 'と', ro: 'to', ko: '토' },
  ],
  na: [
    { jp: 'な', ro: 'na', ko: '나' },
    { jp: 'に', ro: 'ni', ko: '니' },
    { jp: 'ぬ', ro: 'nu', ko: '누' },
    { jp: 'ね', ro: 'ne', ko: '네' },
    { jp: 'の', ro: 'no', ko: '노' },
  ],
  ha: [
    { jp: 'は', ro: 'ha', ko: '하' },
    { jp: 'ひ', ro: 'hi', ko: '히' },
    { jp: 'ふ', ro: 'fu', ko: '후' },
    { jp: 'へ', ro: 'he', ko: '헤' },
    { jp: 'ほ', ro: 'ho', ko: '호' },
  ],
  ma: [
    { jp: 'ま', ro: 'ma', ko: '마' },
    { jp: 'み', ro: 'mi', ko: '미' },
    { jp: 'む', ro: 'mu', ko: '무' },
    { jp: 'め', ro: 'me', ko: '메' },
    { jp: 'も', ro: 'mo', ko: '모' },
  ],
  ya: [
    { jp: 'や', ro: 'ya', ko: '야' },
    { jp: 'ゆ', ro: 'yu', ko: '유' },
    { jp: 'よ', ro: 'yo', ko: '요' },
    // { jp: 'ょ', ro: 'yo', ko: '요' },
  ],
  ra: [
    { jp: 'ら', ro: 'ra', ko: '라' },
    { jp: 'り', ro: 'ri', ko: '리' },
    { jp: 'る', ro: 'ru', ko: '루' },
    { jp: 'れ', ro: 're', ko: '레' },
    { jp: 'ろ', ro: 'ro', ko: '로' },
  ],
  wa: [
    { jp: 'わ', ro: 'wa', ko: '와' },
    { jp: 'を', ro: 'wo', ko: '오' },
    { jp: 'ん', ro: 'n', ko: '은/는' },
  ],
  ga: [
    { jp: 'が', ro: 'ga', ko: '가' },
    { jp: 'ぎ', ro: 'gi', ko: '기' },
    { jp: 'ぐ', ro: 'gu', ko: '구' },
    { jp: 'げ', ro: 'ge', ko: '게' },
    { jp: 'ご', ro: 'go', ko: '고' },
  ],
  za: [
    { jp: 'ざ', ro: 'za', ko: '자' },
    { jp: 'じ', ro: 'ji', ko: '지' },
    { jp: 'ず', ro: 'zu', ko: '즈' },
    { jp: 'ぜ', ro: 'ze', ko: '제' },
    { jp: 'ぞ', ro: 'zo', ko: '조' },
  ],
  da: [
    { jp: 'だ', ro: 'da', ko: '다' },
    { jp: 'ぢ', ro: 'ji', ko: '지' },
    { jp: 'づ', ro: 'zu', ko: '즈' },
    { jp: 'で', ro: 'de', ko: '데' },
    { jp: 'ど', ro: 'do', ko: '도' },
  ],
  ba: [
    { jp: 'ば', ro: 'ba', ko: '바' },
    { jp: 'び', ro: 'bi', ko: '비' },
    { jp: 'ぶ', ro: 'bu', ko: '부' },
    { jp: 'べ', ro: 'be', ko: '베' },
    { jp: 'ぼ', ro: 'bo', ko: '보' },
  ],
  pa: [
    { jp: 'ぱ', ro: 'pa', ko: '파' },
    { jp: 'ぴ', ro: 'pi', ko: '피' },
    { jp: 'ぷ', ro: 'pu', ko: '푸' },
    { jp: 'ぺ', ro: 'pe', ko: '페' },
    { jp: 'ぽ', ro: 'po', ko: '포' },
  ],
};

export const katakana = {
  a: [
    { jp: 'ア', ro: 'a', ko: '아' },
    { jp: 'イ', ro: 'i', ko: '이' },
    { jp: 'ウ', ro: 'u', ko: '우' },
    { jp: 'エ', ro: 'e', ko: '에' },
    { jp: 'オ', ro: 'o', ko: '오' },
  ],
  ka: [
    { jp: 'カ', ro: 'ka', ko: '카' },
    { jp: 'キ', ro: 'ki', ko: '키' },
    { jp: 'ク', ro: 'ku', ko: '쿠' },
    { jp: 'ケ', ro: 'ke', ko: '케' },
    { jp: 'コ', ro: 'ko', ko: '코' },
  ],
  sa: [
    { jp: 'サ', ro: 'sa', ko: '사' },
    { jp: 'シ', ro: 'shi', ko: '시' },
    { jp: 'ス', ro: 'su', ko: '스' },
    { jp: 'セ', ro: 'se', ko: '세' },
    { jp: 'ソ', ro: 'so', ko: '소' },
  ],
  ta: [
    { jp: 'タ', ro: 'ta', ko: '타' },
    { jp: 'チ', ro: 'chi', ko: '치' },
    { jp: 'ツ', ro: 'tsu', ko: '츠' },
    { jp: 'テ', ro: 'te', ko: '테' },
    { jp: 'ト', ro: 'to', ko: '토' },
  ],
  na: [
    { jp: 'ナ', ro: 'na', ko: '나' },
    { jp: 'ニ', ro: 'ni', ko: '니' },
    { jp: 'ヌ', ro: 'nu', ko: '누' },
    { jp: 'ネ', ro: 'ne', ko: '네' },
    { jp: 'ノ', ro: 'no', ko: '노' },
  ],
  ha: [
    { jp: 'ハ', ro: 'ha', ko: '하' },
    { jp: 'ヒ', ro: 'hi', ko: '히' },
    { jp: 'フ', ro: 'fu', ko: '후' },
    { jp: 'ヘ', ro: 'he', ko: '헤' },
    { jp: 'ホ', ro: 'ho', ko: '호' },
  ],
  ma: [
    { jp: 'マ', ro: 'ma', ko: '마' },
    { jp: 'ミ', ro: 'mi', ko: '미' },
    { jp: 'ム', ro: 'mu', ko: '무' },
    { jp: 'メ', ro: 'me', ko: '메' },
    { jp: 'モ', ro: 'mo', ko: '모' },
  ],
  ya: [
    { jp: 'ヤ', ro: 'ya', ko: '야' },
    { jp: 'ユ', ro: 'yu', ko: '유' },
    { jp: 'ヨ', ro: 'yo', ko: '요' },
  ],
  ra: [
    { jp: 'ラ', ro: 'ra', ko: '라' },
    { jp: 'リ', ro: 'ri', ko: '리' },
    { jp: 'ル', ro: 'ru', ko: '루' },
    { jp: 'レ', ro: 're', ko: '레' },
    { jp: 'ロ', ro: 'ro', ko: '로' },
  ],
  wa: [
    { jp: 'ワ', ro: 'wa', ko: '와' },
    { jp: 'ヲ', ro: 'wo', ko: '오' },
    { jp: 'ン', ro: 'n', ko: '은/는' },
  ],
  ga: [
    { jp: 'ガ', ro: 'ga', ko: '가' },
    { jp: 'ギ', ro: 'gi', ko: '기' },
    { jp: 'グ', ro: 'gu', ko: '구' },
    { jp: 'ゲ', ro: 'ge', ko: '게' },
    { jp: 'ゴ', ro: 'go', ko: '고' },
  ],
  za: [
    { jp: 'ザ', ro: 'za', ko: '자' },
    { jp: 'ジ', ro: 'ji', ko: '지' },
    { jp: 'ズ', ro: 'zu', ko: '즈' },
    { jp: 'ゼ', ro: 'ze', ko: '제' },
    { jp: 'ゾ', ro: 'zo', ko: '조' },
  ],
  da: [
    { jp: 'ダ', ro: 'da', ko: '다' },
    { jp: 'ヂ', ro: 'ji', ko: '지' },
    { jp: 'ヅ', ro: 'zu', ko: '즈' },
    { jp: 'デ', ro: 'de', ko: '데' },
    { jp: 'ド', ro: 'do', ko: '도' },
  ],
  ba: [
    { jp: 'バ', ro: 'ba', ko: '바' },
    { jp: 'ビ', ro: 'bi', ko: '비' },
    { jp: 'ブ', ro: 'bu', ko: '부' },
    { jp: 'ベ', ro: 'be', ko: '베' },
    { jp: 'ボ', ro: 'bo', ko: '보' },
  ],
  pa: [
    { jp: 'パ', ro: 'pa', ko: '파' },
    { jp: 'ピ', ro: 'pi', ko: '피' },
    { jp: 'プ', ro: 'pu', ko: '푸' },
    { jp: 'ペ', ro: 'pe', ko: '페' },
    { jp: 'ポ', ro: 'po', ko: '포' },
  ],
};

// export const onConvert = (data: Verb) => {
//   const _logic: any = logic.find(({ type = '' }) => type === 'present');

//   const { form = 0, endingro = '', stemjp = '' } = data;

//   const good = _logic['value'][form];
//   const a = good[endingro];

//   const romaji = _logic['value'][form][endingro].split('_');

//   let result = '';
//   romaji.map((o: string) => {
//     Object.values(hiragana).forEach((data) => {
//       const { jp = '' } = data.find(({ ro: _ro }) => _ro === o) || {};
//       if (jp) result += jp;
//     });
//   });
//   return result;
// };
